import React, { createContext, useContext, ReactNode } from 'react';

export type Language = 'bg';

type TranslationParams = Record<string, string | number>;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: TranslationParams) => string;
}

const translations: Record<string, string> = {
    // Header
    'header.title': 'ЛАТЕЛИНА',
    'header.subtitle': 'Ръчно изработени подаръци',
    'header.search': 'Търсене...',
    'header.phone': '+359 2 123 4567',
    'header.freeDelivery': 'Безплатна доставка над €25',
    'header.myProfile': 'Моят профил',
    'header.myOrders': 'Моите поръчки',
    'header.help': 'Помощ',
    'header.login': 'Вход',
    'header.register': 'Регистрация',
    'header.logout': 'Изход',
    'header.settings': 'Настройки на профила',
    'header.adminPanel': 'Админ панел',
    'header.staffPanel': 'Служителски панел',
    'header.hello': 'Здравейте',
    'header.administrator': 'Администратор',
    'header.staffMember': 'Служител',

    // Navigation
    'navigation.home': 'Начало',
    'navigation.categories': 'Магазин',
    'navigation.products': 'Колекции',
    'navigation.promotions': 'Промоции',
    'navigation.news': 'За нас',
    'navigation.contacts': 'Контакти',

    // Hero Section
    'hero.title': 'ЛАТЕЛИНА',
    'hero.description': 'Ръчно изработени мечета от рози, подаръчни кошници и романтични изненади.',
    'hero.certifiedQuality': 'Изработено с любов',
    'hero.support247': 'Лесна онлайн поръчка',
    'hero.expressDelivery': 'Бърза доставка',
    'hero.qualityAwards': 'Споделени моменти',
    'hero.viewProducts': 'Разгледайте магазина',
    'hero.contactTeam': 'Пишете ни',
    'hero.satisfiedClients': 'Усмихнати клиенти',
    'hero.productsInStock': 'Идеи за подарък',
    'hero.professionalCare': 'Лична грижа',

    // Home Page
    'home.dateTime.title': 'Текуща дата и час',
    'home.dateTime.localDate': 'Дата',
    'home.dateTime.localTime': 'Час',
    'home.promotionsTitle': 'Актуални промоции',
    'home.promotionsSubtitle': 'Нежни изненади и романтични комплекти на специални цени.',
    'home.promotionsViewAll': 'Виж всички промоции',
    'home.promotionsEmpty': 'В момента няма активни промоции. Проверете отново скоро.',

    // Categories
    'categories.title': 'Категории подаръци',
    'categories.subtitle': 'Разгледайте нашите селекции и изберете подарък за любим човек.',
    'categories.previewSubtitle': 'Най-търсените романтични предложения.',
    'categories.viewAll': 'Виж всички категории',
    'categories.viewProducts': 'Виж продуктите',
    'categories.searchLabel': 'Търсене в категории',
    'categories.searchPlaceholder': 'Филтрирайте по име или описание...',
    'categories.sortLabel': 'Сортиране',
    'categories.sortPopular': 'По популярност',
    'categories.sortAlphabetical': 'По азбучен ред',
    'categories.sortProducts': 'Най-много продукти',
    'categories.preview': 'Преглед',
    'categories.all': 'Всички',
    'categories.painkillers': 'Романтични подаръци',
    'categories.vitamins': 'Подаръчни комплекти',
    'categories.coldFlu': 'Специални поводи',
    'categories.digestive': 'Домашен уют',
    'categories.skinHair': 'Блясък и стил',
    'categories.children': 'За всички възрасти',

    // Products
    'products.featuredTitle': 'Акцентирани подаръци',
    'products.featuredSubtitle': 'Подбрани артикули за специални моменти.',
    'products.resultsFor': 'Резултати за',
    'products.category': 'Категория',
    'products.unknown': 'Неизвестна',
    'products.allProducts': 'Всички продукти',
    'products.products': 'продукта',
    'products.noProducts': 'Няма намерени продукти',
    'products.tryDifferent': 'Опитайте с различни ключови думи или разгледайте нашите категории',
    'products.viewAll': 'Разгледайте всички подаръци',
    'products.showLess': 'Покажи по-малко',
    'products.manufacturer': 'Производител',
    'products.inStock': 'В наличност',
    'products.outOfStock': 'Няма в наличност',
    'products.pieces': 'бр.',
    'products.add': 'Добави',
    'products.moreInfo': 'Повече информация',
    'products.productDetails': 'Детайли за продукта',
    'products.descriptionLabel': 'Описание',
    'products.stockStatus': 'Наличност',
    'products.promotionValidUntil': 'Промоцията е валидна до',
    'products.viewDetails': 'Виж детайли',
    'products.reviews': 'отзива',
    'products.catalogTitle': 'Каталог подаръци',
    'products.catalogDescription': 'Вижте целия избор от мечета от рози, кошници и романтични жестове.',
    'products.categoryOverview': 'Категории и наличности',
    'products.categoryOverviewDescription': 'Бърз поглед върху основните ни категории и налични продукти.',
    'products.totalProductsLabel': 'Общо продукти',
    'products.inCategory': 'В категорията',
    'products.filtersTitle': 'Филтриране',
    'products.filtersSubtitle': 'Прецизирайте търсенето според вашите нужди.',
    'products.searchInCatalog': 'Търсене в каталога',
    'products.searchPlaceholder': 'Търсете по име, състав или описание...',
    'products.priceRange': 'Ценови диапазон',
    'products.minPrice': 'Мин. цена',
    'products.maxPrice': 'Макс. цена',
    'products.availability': 'Наличност',
    'products.availabilityAll': 'Всички',
    'products.availabilityInStock': 'В наличност',
    'products.availabilityOutOfStock': 'Няма наличност',
    'products.promotionsOnly': 'Само промоции',
    'products.sortBy': 'Подреди по',
    'products.sortPopular': 'Препоръчани',
    'products.sortPriceLowHigh': 'Цена: ниска към висока',
    'products.sortPriceHighLow': 'Цена: висока към ниска',
    'products.clearFilters': 'Изчисти филтрите',
    'products.moreInfoTitle': 'Допълнителна информация',
    'products.moreInfoSubtitle':
      'Скоро ще добавим подробни указания, листовки и препоръки за прием за всеки продукт.',
    'products.moreInfoPlaceholder':
      'Тук ще откриете официалната листовка, допълнителни съвети за употреба и важни предупреждения.',
    'products.moreInfoNotFoundTitle': 'Продуктът не беше намерен',
    'products.moreInfoNotFoundDescription': 'Моля, върнете се към каталога и изберете друг продукт.',

    // Cart
    'cart.title': 'Количка',
    'cart.empty': 'Количката е празна',
    'cart.emptyDescription': 'Добавете продукти, за да продължите с поръчката',
    'cart.continueShopping': 'Продължете пазаруването',
    'cart.remove': 'Премахни',
    'cart.total': 'Общо',
    'cart.freeDelivery': '✓ Безплатна доставка',
    'cart.loginRequired': 'Влезте в профила си, за да завършите поръчката.',
    'cart.regularPrice': 'Стандартна цена',
    'cart.promoPrice': 'Промо цена',
    'cart.addForFreeDelivery': 'Добавете продукти за €{amount} за безплатна доставка',
    'cart.checkout': 'Финализиране на поръчка',

    // Checkout
    'checkout.title': 'Финализиране на поръчката',
    'checkout.subtitle': 'Попълнете данните си за доставка и контакт.',
    'checkout.section.payment': 'Метод на плащане',
    'checkout.section.summary': 'Обобщение на поръчката',
    'checkout.field.fullName': 'Пълно име',
    'checkout.field.email': 'Имейл адрес',
    'checkout.field.phone': 'Телефон',
    'checkout.field.address': 'Адрес',
    'checkout.field.city': 'Град',
    'checkout.field.postalCode': 'Пощенски код',
    'checkout.field.country': 'Държава',
    'checkout.field.notes': 'Бележки към поръчката',
    'checkout.paymentUnavailable': 'Плащането ще бъде активирано в продукционна среда. Изберете метод и завършете поръчката.',
    'checkout.payment.cashOnDelivery': 'Наложен платеж',
    'checkout.payment.card': 'Карта',
    'checkout.payment.bankTransfer': 'Банков превод',
    'checkout.summary.subtotal': 'Продукти',
    'checkout.summary.delivery': 'Доставка',
    'checkout.summary.free': 'Безплатно',
    'checkout.summary.total': 'Общо за плащане',
    'checkout.actions.cancel': 'Откажи',
    'checkout.actions.submit': 'Завърши поръчката',
    'checkout.validation.noItems': 'Добавете продукти, за да завършите поръчката.',
    'checkout.validation.missingSession': 'Моля, влезте отново, за да продължите.',
    'checkout.error.generic': 'Възникна грешка при създаването на поръчката.',
    'checkout.success.title': 'Поръчката е приета!',
    'checkout.success.message': 'Ще ви уведомим, когато започнем обработката.',
    'checkout.success.hint': 'Проследявайте всички поръчки в секцията „Моите поръчки“.',
    'checkout.success.close': 'Затвори',

    // Auth
    'auth.login': 'Вход',
    'auth.loginSubtitle': 'Влезте в профила си',
    'auth.register': 'Регистрация',
    'auth.registerSubtitle': 'Създайте нов акаунт',
    'auth.email': 'Имейл адрес',
    'auth.password': 'Парола',
    'auth.confirmPassword': 'Потвърдете паролата',
    'auth.fullName': 'Пълно име',
    'auth.firstName': 'Име',
    'auth.lastName': 'Фамилия',
    'auth.phone': 'Телефон',
    'auth.address': 'Адрес',
    'auth.age': 'Години',
    'auth.gender': 'Пол',
    'auth.male': 'Мъж',
    'auth.female': 'Жена',
    'auth.other': 'Друг',
    'auth.rememberMe': 'Запомни ме',
    'auth.forgotPassword': 'Забравена парола?',
    'auth.loginButton': 'Влез',
    'auth.registerButton': 'Регистрирай се',
    'auth.loggingIn': 'Влизане...',
    'auth.registering': 'Регистриране...',
    'auth.noAccount': 'Нямате акаунт?',
    'auth.haveAccount': 'Вече имате акаунт?',
    'auth.loginHere': 'Влезте тук',
    'auth.registerHere': 'Регистрирайте се',
    'auth.admin': 'Админ',
    'auth.customers': 'Клиенти',
    'auth.user': 'Потребител',
    'auth.required': 'Задължително поле',
    'auth.passwordsNotMatch': 'Паролите не съвпадат',
    'auth.loginError': 'Грешка при вход',
    'auth.registerError': 'Грешка при регистрация',
    'auth.networkError': 'Мрежова грешка',
    'auth.loginSuccess': 'Успешен вход',
    'auth.registerSuccess': 'Регистрацията е успешна! Можете да влезете в профила си.',
    'auth.twoFactorTitle': 'Двуфакторна верификация',
    'auth.twoFactorSubtitle': 'Въведете кода, изпратен на вашия имейл',
    'auth.twoFactorCodeLabel': 'Код за потвърждение',
    'auth.twoFactorCodePlaceholder': 'Напр. 123456',
    'auth.twoFactorSubmit': 'Потвърди кода',
    'auth.twoFactorChecking': 'Проверка...',
    'auth.twoFactorBack': 'Върни се към входа',
    'auth.twoFactorResend': 'Изпрати нов код',
    'auth.twoFactorResending': 'Изпращане...',
    'auth.twoFactorInvalid': 'Невалиден код за верификация',
    'auth.twoFactorResent': 'Изпратихме нов код за потвърждение.',
    'auth.twoFactorResendError': 'Грешка при изпращане на нов код',
    'auth.twoFactorSentTo': 'Кодът беше изпратен до',
    'auth.twoFactorExpiresAt': 'Кодът е валиден до',

    // Profile Settings
    'profile.title': 'Настройки на профила',
    'profile.subtitle': 'Актуализирайте своята основна информация и контакти.',
    'profile.email': 'Имейл адрес',
    'profile.readonlyEmail': 'Имейл адресът не може да бъде променян.',
    'profile.adminBadge': 'Администратор',
    'profile.staffBadge': 'Служител',
    'profile.fullName': 'Пълно име',
    'profile.fullNamePlaceholder': 'Иван Иванов',
    'profile.phoneNumber': 'Телефон',
    'profile.phonePlaceholder': '+359 88 123 4567',
    'profile.address': 'Адрес',
    'profile.addressPlaceholder': 'гр. София, ул. „Пример“ 1',
    'profile.reset': 'Възстанови',
    'profile.save': 'Запази промените',
    'profile.saving': 'Запазване...',
    'profile.success': 'Профилът беше обновен успешно.',
    'profile.error': 'Възникна грешка при обновяване на профила.',
    'profile.notAuthenticated': 'За да редактирате профила си, трябва да влезете.',

    // Orders
    'orders.modal.title': 'Моите поръчки',
    'orders.modal.subtitle': 'Проследявайте статуса и детайлите на последните си поръчки.',
    'orders.loading': 'Зареждане на поръчките...',
    'orders.actions.retry': 'Опитай отново',
    'orders.actions.refresh': 'Обнови',
    'orders.errors.noSession': 'Няма активна сесия. Моля, влезте отново.',
    'orders.errors.fetchFailed': 'Неуспешно зареждане на поръчките.',
    'orders.errors.notAuthenticated': 'За да видите поръчките си, трябва да влезете.',
    'orders.empty.title': 'Все още нямате поръчки',
    'orders.empty.subtitle': 'След като направите поръчка, тя ще се появи тук.',
    'orders.status.pending': 'В изчакване',
    'orders.status.confirmed': 'Потвърдена',
    'orders.status.processing': 'Обработва се',
    'orders.status.shipped': 'Изпратена',
    'orders.status.delivered': 'Доставена',
    'orders.status.cancelled': 'Отказана',
    'orders.detail.orderNumber': 'Номер на поръчка',
    'orders.detail.paymentMethod': 'Метод на плащане',
    'orders.detail.total': 'Обща сума',
    'orders.detail.items': 'Продукти в поръчката',
    'orders.detail.placedOn': 'Поръчана на {date}',
    'orders.detail.deliveryStatus': 'Статус на доставката',

    // Admin Panel
    'admin.panel.title': 'Администраторски панел',
    'admin.panel.subtitle': 'Управлявайте потребителите и техните права',
    'admin.panel.description': 'Вижте списъка с потребители, редактирайте данни и контролирайте достъпа до платформата.',
    'admin.panel.staffTitle': 'Служителски панел',
    'admin.panel.staffSubtitle': 'Следете клиентските профили и поръчки',
    'admin.panel.staffDescription':
      'Обработвайте поръчки, актуализирайте клиентски данни и публикувайте новини за аптеката.',
    'admin.loading': 'Зареждане на админ панела...',
    'admin.panel.tabs.users': 'Потребители',
    'admin.panel.tabs.permissions': 'Права',
    'admin.panel.tabs.orders': 'Поръчки',
    'admin.panel.tabs.products': 'Каталог',
    'admin.panel.tabs.news': 'Новини',
    'admin.users.searchLabel': 'Търсене на потребители',
    'admin.users.searchPlaceholder': 'Име, имейл или телефон...',
    'admin.users.errors.noSession': 'Не е намерен валиден админ токен. Влезте отново.',
    'admin.users.errors.fetchFailed': 'Неуспешно зареждане на потребителите.',
    'admin.users.errors.saveFailed': 'Неуспешно запазване на промените.',
    'admin.users.errors.staffForbidden': 'Нямате права да редактирате този потребител.',
    'admin.users.retry': 'Опитайте отново',
    'admin.users.badges.admin': 'Администратор',
    'admin.users.badges.staff': 'Служител',
    'admin.users.badges.deactivated': 'Деактивиран',
    'admin.users.badges.active': 'Активен',
    'admin.users.empty': 'Няма намерени потребители.',
    'admin.users.unknownName': 'Няма име',
    'admin.users.memberSince': 'Член от {date}',
    'admin.users.saveSuccess': 'Потребителят е обновен успешно.',
    'admin.users.restrictedNotice':
      'Можете да редактирате само стандартни потребители. Администраторите и служителите са защитени.',
    'admin.users.permissions.title': 'Права и статус',
    'admin.users.permissions.admin': 'Администраторски права',
    'admin.users.permissions.deactivate': 'Маркирай като деактивиран',
    'admin.users.permissions.selfWarning': 'Внимание: променяте собствения си акаунт. Не премахвайте администраторските права, ако се нуждаете от достъп.',
    'admin.permissions.instructions': 'Изберете нивото на достъп за избрания профил. Служителите могат да обработват поръчки и да следят заявки, но нямат достъп до всички системни настройки.',
    'admin.permissions.sectionTitle': 'Управление на достъпа',
    'admin.permissions.admin': 'Пълен администраторски достъп',
    'admin.permissions.staff': 'Оперативен достъп (служител)',
    'admin.permissions.manageProducts': 'Управление на каталога',
    'admin.permissions.deactivate': 'Маркирай акаунта като деактивиран',
    'admin.permissions.save': 'Запази правата',
    'admin.permissions.saving': 'Запазване на правата...',
    'admin.users.fields.email': 'Имейл',
    'admin.users.fields.fullName': 'Пълно име',
    'admin.users.fields.fullNamePlaceholder': 'Име и фамилия',
    'admin.users.fields.phone': 'Телефон',
    'admin.users.fields.phonePlaceholder': 'Мобилен телефон',
    'admin.users.fields.address': 'Адрес',
    'admin.users.fields.addressPlaceholder': 'Адрес за доставка',
    'admin.users.actions.reset': 'Отмени промените',
    'admin.users.actions.refresh': 'Презареди',
    'admin.users.actions.saving': 'Запазване...',
    'admin.users.actions.save': 'Запази',
    'admin.users.noSelection': 'Изберете потребител от списъка, за да редактирате неговите данни.',

    'admin.orders.title': 'Всички поръчки',
    'admin.orders.subtitle': 'Следете поръчките от всички потребители в платформата.',
    'admin.orders.count': 'Поръчки: {count}',
    'admin.orders.refresh': 'Обнови',
    'admin.orders.loading': 'Зареждане на поръчките...',
    'admin.orders.retry': 'Опитай отново',
    'admin.orders.empty': 'Няма намерени поръчки.',
    'admin.orders.customer': 'Клиент',
    'admin.orders.unknownCustomer': 'Неизвестен клиент',
    'admin.orders.summary.total': 'Общо (с доставка)',
    'admin.orders.actions.title': 'Статус на поръчката',
    'admin.orders.actions.pending': 'Маркирай като чакаща',
    'admin.orders.actions.confirm': 'Потвърди',
    'admin.orders.actions.process': 'Започни обработка',
    'admin.orders.actions.ship': 'Изпрати',
    'admin.orders.actions.deliver': 'Достави',
    'admin.orders.actions.cancel': 'Откажи',
    'admin.orders.status.updated': 'Статусът на поръчката е обновен.',
    'admin.orders.errors.noSession': 'Няма активна сесия. Моля, влезте отново.',
    'admin.orders.errors.fetchFailed': 'Неуспешно зареждане на поръчките.',
    'admin.orders.errors.updateFailed': 'Неуспешно обновяване на статуса на поръчката.',

    'admin.products.title': 'Продуктов каталог',
    'admin.products.subtitle': 'Добавяйте, редактирайте и следете артикулите в магазина.',
    'admin.products.count': 'Продукти: {count}',
    'admin.products.searchLabel': 'Търсене в каталога',
    'admin.products.searchPlaceholder': 'Име, производител или описание...',
    'admin.products.empty': 'Няма намерени артикули.',
    'admin.products.unknownCategory': 'Без категория',
    'admin.products.readOnlyNotice': 'Преглеждате каталога в режим само за четене.',
    'admin.products.labels.promo': 'Промоция',
    'admin.products.actions.new': 'Нов артикул',
    'admin.products.actions.reset': 'Върни промените',
    'admin.products.actions.save': 'Запази',
    'admin.products.actions.create': 'Създай',
    'admin.products.actions.delete': 'Изтрий',
    'admin.products.actions.confirmDelete': 'Изтрий артикула',
    'admin.products.actions.cancelDelete': 'Откажи',
    'admin.products.actions.saving': 'Запазване...',
    'admin.products.form.createTitle': 'Нов артикул',
    'admin.products.form.createSubtitle': 'Въведете информацията и запазете, за да добавите артикул.',
    'admin.products.form.editTitle': 'Редакция на артикул',
    'admin.products.form.editSubtitle': 'Актуализирайте детайлите и запазете промените.',
    'admin.products.form.section.details': 'Основна информация',
    'admin.products.form.section.detailsSubtitle': 'Име, описание, цена и наличности.',
    'admin.products.form.section.composition': 'Състав и дозировка',
    'admin.products.form.section.compositionSubtitle': 'Активни съставки, дозировка и производител.',
    'admin.products.form.section.promotion': 'Промоционални условия',
    'admin.products.form.section.promotionSubtitle': 'Активирайте, ако продуктът има текуща промоция.',
    'admin.products.form.fields.nameBg': 'Име (BG)',
    'admin.products.form.fields.descriptionBg': 'Описание (BG)',
    'admin.products.form.fields.price': 'Цена (€)',
    'admin.products.form.fields.stock': 'Наличност',
    'admin.products.form.fields.category': 'Категория',
    'admin.products.form.fields.categoryPlaceholder': 'Изберете категория',
    'admin.products.form.fields.imageUrl': 'URL на изображение',
    'admin.products.form.fields.manufacturerBg': 'Производител (BG)',
    'admin.products.form.fields.enablePromotion': 'Активирай промоция',
    'admin.products.form.fields.promotionId': 'Идентификатор на промоцията',
    'admin.products.form.fields.promotionTitleBg': 'Заглавие (BG)',
    'admin.products.form.fields.promotionPrice': 'Промо цена (€)',
    'admin.products.form.fields.promotionDiscount': 'Отстъпка (%)',
    'admin.products.form.fields.promotionValidUntil': 'Валидна до',
    'admin.products.form.fields.promotionDescriptionBg': 'Описание (BG)',
    'admin.products.form.fields.promotionBadge': 'Цвят на значката',
    'admin.products.form.fields.promotionBadgePlaceholder': 'Без значка',
    'admin.products.form.fields.badge.emerald': 'Зелена',
    'admin.products.form.fields.badge.blue': 'Синя',
    'admin.products.form.fields.badge.purple': 'Лилава',
    'admin.products.form.fields.badge.orange': 'Оранжева',
    'admin.products.form.fields.badge.pink': 'Розова',
    'admin.products.errors.listTitle': 'Проверете следните полета:',
    'admin.products.errors.name': 'Въведете име на български.',
    'admin.products.errors.price': 'Въведете валидна цена по-голяма от нула.',
    'admin.products.errors.stock': 'Наличността не може да е отрицателна.',
    'admin.products.errors.category': 'Изберете категория.',
    'admin.products.errors.imageUrl': 'Добавете URL на изображението.',
    'admin.products.errors.promotionTitle': 'Въведете заглавие на промоцията на български.',
    'admin.products.errors.promoPrice': 'Въведете валидна промоционална цена.',
    'admin.products.errors.promoPriceCompare': 'Промоционалната цена трябва да е по-ниска от стандартната.',
    'admin.products.errors.discount': 'Отстъпката трябва да е между 0 и 100%.',
    'admin.products.errors.general': 'Моля, прегледайте отбелязаните полета.',
    'admin.products.delete.title': 'Изтриване на артикул',
    'admin.products.delete.description': 'Сигурни ли сте, че искате да изтриете „{name}“?',
    'admin.products.messages.created': 'Артикулът беше създаден успешно.',
    'admin.products.messages.updated': 'Артикулът беше обновен успешно.',
    'admin.products.messages.deleted': 'Артикулът беше изтрит.',

    'admin.news.listTitle': 'Публикувани новини',
    'admin.news.listSubtitle': 'Преглеждайте последните публикации и техните корици.',
    'admin.news.empty': 'Все още няма добавени статии.',
    'admin.news.article.author': 'Автор: {author}',
    'admin.news.editTitle': 'Редактиране на статия',
    'admin.news.editSubtitle': 'Коригирайте съдържанието и запазете промените.',
    'admin.news.createTitle': 'Създаване на нова статия',
    'admin.news.createSubtitle': 'Попълнете информацията и добавете публикацията към блога.',
    'admin.news.messages.created': 'Новината беше създадена успешно.',
    'admin.news.messages.updated': 'Новината беше обновена успешно.',
    'admin.news.messages.deleted': 'Новината беше изтрита.',
    'admin.news.messages.imageGenerated': 'Генерирахме иконка за тази новина.',
    'admin.news.actions.new': 'Нова статия',
    'admin.news.actions.edit': 'Редактирай',
    'admin.news.actions.delete': 'Изтрий',
    'admin.news.actions.editing': 'В режим на редакция',
    'admin.news.actions.openForEditing': 'Отвори „{title}“ за редакция',
    'admin.news.actions.cancelEdit': 'Откажи редакцията',
    'admin.news.errors.listTitle': 'Проверете следните полета:',
    'admin.news.errors.general': 'Моля, коригирайте отбелязаните полета.',
    'admin.news.errors.title': 'Въведете заглавие на български.',
    'admin.news.errors.excerpt': 'Добавете кратко резюме на български.',
    'admin.news.errors.content': 'Въведете съдържание на български.',
    'admin.news.errors.category': 'Добавете категория на български.',
    'admin.news.errors.author': 'Посочете автор на статията.',
    'admin.news.errors.imageUrl': 'Добавете изображение или генерирайте автоматично.',
    'admin.news.errors.publishedAt': 'Изберете валидна дата на публикуване.',
    'admin.news.errors.readTime': 'Въведете време за четене (минимум 1 минута).',
    'admin.news.errors.readTimeRange': 'Времето за четене трябва да е до 60 минути.',
    'admin.news.form.identifierLabel': 'Идентификатор (по избор)',
    'admin.news.form.identifierPlaceholder': 'напр. winter-immunity-2025',
    'admin.news.form.identifierHelp': 'Ако оставите празно, системата ще създаде автоматичен идентификатор.',
    'admin.news.form.titleBg': 'Заглавие (BG)',
    'admin.news.form.excerptBg': 'Резюме (BG)',
    'admin.news.form.contentBg': 'Съдържание (BG)',
    'admin.news.form.categoryBg': 'Категория (BG)',
    'admin.news.form.author': 'Автор',
    'admin.news.form.imageUrl': 'URL на изображение',
    'admin.news.form.imageUrlHelp': 'Използвайте собствена снимка или натиснете „Генерирай“, за да създадете графика.',
    'admin.news.form.generateImage': 'Генерирай',
    'admin.news.form.generatedTitleFallback': 'Latelina Insight',
    'admin.news.form.generatedCategoryFallback': 'Обновления в магазина',
    'admin.news.form.publishedAt': 'Дата на публикуване',
    'admin.news.form.readTime': 'Време за четене (минути)',
    'admin.news.form.reset': 'Изчисти формата',
    'admin.news.form.resetEditing': 'Върни оригинала',
    'admin.news.form.submit': 'Публикувай статия',
    'admin.news.form.submitUpdate': 'Запази промените',
    'admin.news.form.submitting': 'Публикуване...',
    'admin.news.delete.title': 'Потвърждение за изтриване',
    'admin.news.delete.description': 'Сигурни ли сте, че искате да изтриете „{title}“?',
    'admin.news.delete.confirm': 'Да, изтрий',
    'admin.news.delete.cancel': 'Отказ',

    // Footer
    'footer.title': 'ЛАТЕЛИНА',
    'footer.description': 'Ръчно изработени подаръци, които носят усмивки и създават спомени.',
    'footer.version': 'Версия {version}',
    'footer.quickLinks': 'Бързи връзки',
    'footer.aboutUs': 'За нас',
    'footer.products': 'Продукти',
    'footer.services': 'Услуги',
    'footer.contacts': 'Контакти',
    'footer.promotions': 'Промоции',
    'footer.news': 'Новини',
    'footer.faq': 'Често задавани въпроси',
    'footer.contactsTitle': 'Контакти',
    'footer.workingHours': 'Работно време',
    'footer.workingHoursText': 'Пон-Пет: 8:00 - 22:00\nСъб-Нед: 9:00 - 20:00',
    'footer.copyright': '© 2025 Latelina. Всички права запазени.',
    'footer.privacy': 'Политика за поверителност',
    'footer.terms': 'Условия за ползване',
    'footer.cookies': 'Бисквитки',
    'footer.feedbackTitle': 'Споделете мнението си',
    'footer.feedbackDescription': 'Вашата обратна връзка ни помага да подобряваме магазина и обслужването на ЛАТЕЛИНА.',
    'footer.ratingLabel': 'Оценка',
    'footer.starsLabel': 'звезди',
    'footer.messageLabel': 'Отзив',
    'footer.messagePlaceholder': 'Опишете вашето впечатление, какво харесвате и какво можем да подобрим...',
    'footer.feedbackPrivacy': 'Мнението ви ще бъде изпратено по имейл до екипа на ЛАТЕЛИНА',
    'footer.submitButton': 'Изпрати по имейл',
    'footer.feedbackEmailSubject': 'Обратна връзка за ЛАТЕЛИНА',

    // Common
    'common.loading': 'Зареждане...',
    'common.error': 'Грешка',
    'common.success': 'Успех',
    'common.cancel': 'Отказ',
    'common.save': 'Запази',
    'common.delete': 'Изтрий',
    'common.edit': 'Редактирай',
    'common.close': 'Затвори',
    'common.back': 'Назад',
    'common.next': 'Напред',
    'common.previous': 'Предишна',
    'common.search': 'Търсене',
    'common.filter': 'Филтър',
    'common.sort': 'Сортиране',
    'common.price': 'Цена',
    'common.quantity': 'Количество',
    'common.total': 'Общо',
    'common.currency': '€',

    // About Us
    'about.description': 'Лателина е бутиков онлайн магазин за романтични подаръци и изработени на ръка детайли.',
    'about.mission': 'Нашата мисия',
    'about.missionText': 'Да ви помогнем да кажете „обичам те“ по красив и личен начин.',
    'about.vision': 'Нашата визия',
    'about.visionText': 'Да бъдем любимо място за подаръци, които се помнят и пазят.',
    'about.quality': 'Качество',
    'about.qualityText': 'Избираме нежни материи, фини детайли и внимателно опаковане.',
    'about.speed': 'Бързина',
    'about.speedText': 'Подготвяме и изпращаме подаръците ви максимално бързо и сигурно.',
    'about.care': 'Грижа',
    'about.careText': 'Съдействащ екип, готов да предложи идеи и персонализация.',
    'about.clients': 'Усмихнати клиенти',
    'about.products': 'Идеи в наличност',
    'about.experience': 'Години опит',
    'about.support': 'Поддръжка',

    // Services
    'services.pageTitle': 'Как помагаме',
    'services.pageDescription': 'Личен подход, нежни опаковки и идеи за специални поводи.',
    'services.aiConsultationsTitle': 'Идеи за подарък',
    'services.aiConsultationsDescription': 'Ще ви помогнем да подберете подходящи артикули според повода и човека.',
    'services.aiConsultationsFeature1': 'Персонални препоръки',
    'services.aiConsultationsFeature2': 'Съчетаване на цветове и сетове',
    'services.aiConsultationsFeature3': 'Възможност за лично послание',
    'services.customerServiceTitle': 'Онлайн обслужване на клиенти',
    'services.customerServiceDescription': 'Свържете се с нас за въпроси, идеи и насоки при избора.',
    'services.customerServiceFeature1': 'Консултация за избор на подарък',
    'services.customerServiceFeature2': 'Съдействие за поръчки и доставки',
    'services.customerServiceFeature3': 'Личен контакт през чат или телефон',
    'services.deliveryTitle': 'Доставка',
    'services.deliveryDescription': 'Изпращаме в цялата страна с надеждни партньори.',
    'services.deliveryFeature1': 'Проследяване на пратката',
    'services.deliveryFeature2': 'Гъвкави опции за получаване',
    'services.deliveryFeature3': 'Сигурно опаковане',
    'services.valueTitle': 'Защо ЛАТЕЛИНА',
    'services.valueSubtitle': 'Създаваме чувство, а не просто продукт.',
    'services.valuePatients': 'Лична грижа',
    'services.valuePatientsDesc': 'Отговаряме бързо и съдействаме за всяка идея.',
    'services.valueData': 'Детайлност',
    'services.valueDataDesc': 'Следим всеки детайл в изработката и опаковането.',
    'services.valueSupport': 'Поддръжка',
    'services.valueSupportDesc': 'Насреща сме по телефон, чат и имейл.',
    'services.ctaTitle': 'Нужно ви е вдъхновение?',
    'services.ctaDescription': 'Свържете се с нас и ще подготвим идея за вашия повод.',
    'services.ctaButton': 'Пишете ни',

    // Contacts
    'contacts.description': 'Свържете се с нас по всяко време. Нашият екип е готов да ви помогне с всички въпроси.',
    'contacts.info': 'Информация за контакт',
    'contacts.phone': 'Телефон',
    'contacts.email': 'Имейл',
    'contacts.address': 'Адрес',
    'contacts.emergency': 'Спешни случаи',
    'contacts.emergencyText': 'При медицински спешни случаи, моля обърнете се към спешните служби.',
    'contacts.emergencyNumber': 'Спешен номер',
    'contacts.sendMessage': 'Изпратете съобщение',
    'contacts.firstName': 'Име',
    'contacts.lastName': 'Фамилия',
    'contacts.subject': 'Тема',
    'contacts.message': 'Съобщение',
    'contacts.send': 'Изпрати',
    'contacts.firstNamePlaceholder': 'Вашето име',
    'contacts.lastNamePlaceholder': 'Вашата фамилия',
    'contacts.emailPlaceholder': 'your@email.com',
    'contacts.subjectPlaceholder': 'Тема на съобщението',
    'contacts.messagePlaceholder': 'Напишете вашето съобщение тук...',

    // Promotions
    'promotions.description': 'Открийте актуалните романтични предложения и подарете нещо специално.',
    'promotions.currentCount': '{count} активни оферти',
    'promotions.activeOffers': 'Активни оферти',
    'promotions.averageDiscount': 'Средна отстъпка',
    'promotions.highestDiscount': 'Най-висока отстъпка: {value}%',
    'promotions.estimatedSavings': 'Потенциални спестявания',
    'promotions.limitedStock': 'Офертите са валидни до изчерпване на количествата',
    'promotions.noActive': 'В момента няма активни промоции.',
    'promotions.freeDelivery': 'Безплатна доставка',
    'promotions.freeDeliveryDesc': 'Безплатна доставка за всички поръчки над €25 в цялата страна.',
    'promotions.vitamins20': 'Отстъпка за мечета',
    'promotions.vitamins20Desc': 'Специална промо цена за мечета от рози.',
    'promotions.firstOrder': 'Първа поръчка',
    'promotions.firstOrderDesc': '15% отстъпка за нови клиенти при първата им поръчка.',
    'promotions.loyaltyProgram': 'Програма за лоялност',
    'promotions.loyaltyProgramDesc': 'Събирайте точки с всяка покупка и получавайте отстъпки.',
    'promotions.free': 'Безплатно',
    'promotions.points': 'Точки',
    'promotions.permanent': 'Постоянна',
    'promotions.discount': 'отстъпка',
    'promotions.validUntil': 'Валидна до',
    'promotions.useNow': 'Използвай сега',
    'promotions.howToUse': 'Как да използвате промоциите',
    'promotions.step1': 'Изберете продукти',
    'promotions.step1Desc': 'Добавете желаните продукти в количката си.',
    'promotions.step2': 'Приложете код',
    'promotions.step2Desc': 'Въведете промо кода при финализиране.',
    'promotions.step3': 'Спестете пари',
    'promotions.step3Desc': 'Получете отстъпката и завършете поръчката.',

    // News
    'news.title': 'Новини и вдъхновения',
    'news.subtitle': 'Истории, идеи за подаръци и съвети за красиви изненади.',
    'news.latest': 'Последни публикации',
    'news.readMore': 'Прочетете повече',
    'news.showLess': 'Покажи по-малко',
    'news.readTime': '{minutes} мин четене',
    'news.published': 'Публикувано на',
    'news.authorBy': 'Автор:',

    // FAQ
    'faq.description': 'Намерете отговори на най-често задаваните въпроси за нашите услуги.',
    'faq.searchPlaceholder': 'Търсете въпрос...',
    'faq.noResults': 'Няма намерени резултати',
    'faq.tryDifferent': 'Опитайте с различни ключови думи.',
    'faq.stillNeedHelp': 'Все още имате нужда от помощ?',
    'faq.contactSupport': 'Нашият екип за поддръжка е готов да ви помогне.',
    'faq.callUs': 'Обадете се',
    'faq.emailUs': 'Изпратете имейл',
    'faq.q1': 'Колко време отнема доставката?',
    'faq.a1': 'Доставката в София е до 2 часа, а в останалата част на страната - до 24 часа. За спешни случаи предлагаме експресна доставка.',
    'faq.q2': 'Какви методи за плащане приемате?',
    'faq.a2': 'Приемаме плащания с дебитни и кредитни карти, банков превод, както и плащане при доставка (наложен платеж).',
    'faq.q3': 'Предлагате ли персонализирани картички?',
    'faq.a3': 'Да, можем да добавим кратко послание към повечето артикули. Споделете текста си при финализиране на поръчката.',
    'faq.q4': 'Как да получа помощ при избор на подарък?',
    'faq.a4': 'Свържете се с нас през страницата „Контакти“ или по имейл и ще ви помогнем да изберете подходяща изненада.',
    'faq.q5': 'Мога ли да върна продукт?',
    'faq.a5': 'Да, можете да върнете неотворени продукти в рамките на 14 дни от покупката, съгласно закона за защита на потребителите.',
    'faq.q6': 'Как да създам акаунт?',
    'faq.a6': 'Кликнете на "Регистрация" в горния десен ъгъл и попълнете необходимата информация. Акаунтът ви ще бъде активиран веднага.',
    'faq.q7': 'Доставяте ли извън София?',
    'faq.a7': 'Да, доставяме в цялата страна. Доставката извън София отнема до 24 часа.',
    'faq.q8': 'Сигурни ли са личните ми данни?',
    'faq.a8': 'Да, използваме най-високите стандарти за сигурност и криптиране на данните. Вашата информация е напълно защитена.'
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const language: Language = 'bg';
  const setLanguage = (_lang: Language) => {};

  const t = (key: string, params?: TranslationParams): string => {
    const template = translations[key] || key;

    if (!params) {
      return template;
    }

    return Object.entries(params).reduce((result, [paramKey, value]) => {
      const pattern = new RegExp(`{${paramKey}}`, 'g');
      return result.replace(pattern, String(value));
    }, template);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
