import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'bg' | 'en';

type TranslationParams = Record<string, string | number>;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: TranslationParams) => string;
}

const translations = {
  bg: {
    // Header
    'header.title': 'AIPHARM+',
    'header.subtitle': 'AI аптека и асистент',
    'header.search': 'Търсете лекарства, витамини, козметика...',
    'header.phone': '+359 2 123 4567',
    'header.freeDelivery': 'Безплатна доставка над €25',
    'header.myProfile': 'Моят профил',
    'header.myOrders': 'Моите поръчки',
    'header.help': 'Помощ',
    'header.login': 'Вход',
    'header.register': 'Регистрация',
    'header.logout': 'Изход',
    'header.settings': 'Настройки на профила',
    'header.adminPanel': 'Админ панел',
    'header.staffPanel': 'Служителски панел',
    'header.hello': 'Здравейте',
    'header.administrator': 'Администратор',
    'header.staffMember': 'Служител',

    // Navigation
    'navigation.categories': 'Категории',
    'navigation.products': 'Продукти',
    'navigation.promotions': 'Промоции',
    'navigation.news': 'Новини',

    // Hero Section
    'hero.title': 'AIPHARM+',
    'hero.description': 'Качествени лекарства с AI консултации и бърза доставка',
    'hero.certifiedQuality': 'Сертифицирано качество',
    'hero.support247': '24/7 Поддръжка',
    'hero.expressDelivery': 'Експресна доставка',
    'hero.qualityAwards': 'Награди за качество',
    'hero.viewProducts': 'Разгледайте продуктите',
    'hero.aiAssistant': 'AI Медицински асистент',
    'hero.satisfiedClients': 'Доволни клиенти',
    'hero.productsInStock': 'Продукта в наличност',
    'hero.professionalCare': 'Професионална грижа',

    // Home Page
    'home.dateTime.title': 'Текуща дата и час',
    'home.dateTime.localDate': 'Дата',
    'home.dateTime.localTime': 'Час',
    'home.promotionsTitle': 'Актуални промоции',
    'home.promotionsSubtitle': 'Специални предложения с ограничена валидност за вашето здраве.',
    'home.promotionsViewAll': 'Виж всички промоции',
    'home.promotionsEmpty': 'В момента няма активни промоции. Проверете отново скоро.',

    // Categories
    'categories.title': 'Категории',
    'categories.subtitle': 'Разгледайте нашите основни категории и открийте подходящите продукти.',
    'categories.previewSubtitle': 'Бърз поглед към някои от най-популярните ни категории.',
    'categories.viewAll': 'Виж всички категории',
    'categories.viewProducts': 'Виж продуктите',
    'categories.searchLabel': 'Търсене в категории',
    'categories.searchPlaceholder': 'Филтрирайте по име или описание...',
    'categories.sortLabel': 'Сортиране',
    'categories.sortPopular': 'По популярност',
    'categories.sortAlphabetical': 'По азбучен ред',
    'categories.sortProducts': 'Най-много продукти',
    'categories.preview': 'Преглед',
    'categories.all': 'Всички',
    'categories.painkillers': 'Обезболяващи',
    'categories.vitamins': 'Витамини',
    'categories.coldFlu': 'Простуда и грип',
    'categories.digestive': 'Стомашно-чревни',
    'categories.skinHair': 'Кожа и коса',
    'categories.children': 'Детски продукти',

    // Products
    'products.featuredTitle': 'Акцентирани продукти',
    'products.featuredSubtitle': 'Показваме селекция от най-търсените ни предложения.',
    'products.resultsFor': 'Резултати за',
    'products.category': 'Категория',
    'products.unknown': 'Неизвестна',
    'products.allProducts': 'Всички продукти',
    'products.products': 'продукта',
    'products.noProducts': 'Няма намерени продукти',
    'products.tryDifferent': 'Опитайте с различни ключови думи или разгледайте нашите категории',
    'products.viewAll': 'Разгледайте всички продукти',
    'products.showLess': 'Покажи по-малко',
    'products.prescription': 'Рецепта',
    'products.activeIngredient': 'Активна съставка',
    'products.dosage': 'Дозировка',
    'products.manufacturer': 'Производител',
    'products.inStock': 'В наличност',
    'products.outOfStock': 'Няма в наличност',
    'products.pieces': 'бр.',
    'products.add': 'Добави',
    'products.askAssistant': 'Попитай AI асистента',
    'products.moreInfo': 'Повече информация',
    'products.productDetails': 'Детайли за продукта',
    'products.descriptionLabel': 'Описание',
    'products.prescriptionRequiredLabel': 'Режим на отпускане',
    'products.stockStatus': 'Наличност',
    'products.promotionValidUntil': 'Промоцията е валидна до',
    'products.viewDetails': 'Виж детайли',
    'products.reviews': 'отзива',
    'products.catalogTitle': 'Каталог продукти',
    'products.catalogDescription': 'Разгледайте пълната гама от лекарства, добавки и козметика, подбрани от нашите специалисти.',
    'products.categoryOverview': 'Категории и наличности',
    'products.categoryOverviewDescription': 'Бърз поглед върху основните ни категории и налични продукти.',
    'products.totalProductsLabel': 'Общо продукти',
    'products.inCategory': 'В категорията',
    'products.filtersTitle': 'Филтриране',
    'products.filtersSubtitle': 'Прецизирайте търсенето според вашите нужди.',
    'products.searchInCatalog': 'Търсене в каталога',
    'products.searchPlaceholder': 'Търсете по име, състав или описание...',
    'products.priceRange': 'Ценови диапазон',
    'products.minPrice': 'Мин. цена',
    'products.maxPrice': 'Макс. цена',
    'products.availability': 'Наличност',
    'products.availabilityAll': 'Всички',
    'products.availabilityInStock': 'В наличност',
    'products.availabilityOutOfStock': 'Няма наличност',
    'products.prescriptionFilter': 'Нужда от рецепта',
    'products.requiresPrescription': 'С рецепта',
    'products.overTheCounter': 'Без рецепта',
    'products.promotionsOnly': 'Само промоции',
    'products.sortBy': 'Подреди по',
    'products.sortPopular': 'Препоръчани',
    'products.sortPriceLowHigh': 'Цена: ниска към висока',
    'products.sortPriceHighLow': 'Цена: висока към ниска',
    'products.clearFilters': 'Изчисти филтрите',
    'products.moreInfoTitle': 'Допълнителна информация',
    'products.moreInfoSubtitle':
      'Скоро ще добавим подробни указания, листовки и препоръки за прием за всеки продукт.',
    'products.moreInfoPlaceholder':
      'Тук ще откриете официалната листовка, допълнителни съвети за употреба и важни предупреждения.',
    'products.moreInfoNotFoundTitle': 'Продуктът не беше намерен',
    'products.moreInfoNotFoundDescription': 'Моля, върнете се към каталога и изберете друг продукт.',

    // Cart
    'cart.title': 'Количка',
    'cart.empty': 'Количката е празна',
    'cart.emptyDescription': 'Добавете продукти, за да продължите с поръчката',
    'cart.continueShopping': 'Продължете пазаруването',
    'cart.remove': 'Премахни',
    'cart.total': 'Общо',
    'cart.freeDelivery': '✓ Безплатна доставка',
    'cart.loginRequired': 'Влезте в профила си, за да завършите поръчката.',
    'cart.regularPrice': 'Стандартна цена',
    'cart.promoPrice': 'Промо цена',
    'cart.addForFreeDelivery': 'Добавете продукти за €{amount} за безплатна доставка',
    'cart.checkout': 'Финализиране на поръчка',

    // Checkout
    'checkout.title': 'Финализиране на поръчката',
    'checkout.subtitle': 'Попълнете данните си за доставка и контакт.',
    'checkout.section.prescription': 'Данни за рецепта',
    'checkout.section.personal': 'Лични данни',
    'checkout.section.delivery': 'Данни за доставка',
    'checkout.section.payment': 'Метод на плащане',
    'checkout.section.summary': 'Обобщение на поръчката',
    'checkout.prescription.subtitle': 'За продукти, които се отпускат с рецепта, въведете ЕГН и номер на електронната рецепта.',
    'checkout.prescription.privacy': 'Информацията се използва само за обработка към НЗОК.',
    'checkout.field.fullName': 'Пълно име',
    'checkout.field.email': 'Имейл адрес',
    'checkout.field.phone': 'Телефон',
    'checkout.field.personalId': 'ЕГН',
    'checkout.field.prescriptionNumber': 'Номер на рецепта',
    'checkout.field.address': 'Адрес',
    'checkout.field.city': 'Град',
    'checkout.field.postalCode': 'Пощенски код',
    'checkout.field.country': 'Държава',
    'checkout.field.notes': 'Бележки към поръчката',
    'checkout.paymentUnavailable': 'Плащането ще бъде активирано в продукционна среда. Изберете метод и завършете поръчката.',
    'checkout.payment.cashOnDelivery': 'Наложен платеж',
    'checkout.payment.card': 'Карта',
    'checkout.payment.bankTransfer': 'Банков превод',
    'checkout.prescription.title': 'Необходимо е потвърждение на е-рецепта',
    'checkout.prescription.description':
      'Добавили сте продукт, който изисква рецепта. За да продължите, въведете ЕГН и номера на електронната рецепта.',
    'checkout.prescription.stepTitle': 'е-Рецепта',
    'checkout.prescription.stepSubtitle': 'Попълнете данните от вашата електронна рецепта, за да финализираме поръчката.',
    'checkout.prescription.egn': 'ЕГН',
    'checkout.prescription.code': 'Номер на е-рецепта',
    'checkout.prescription.cardOnly': 'Плащането за продукти с рецепта е възможно само с карта.',
    'checkout.summary.subtotal': 'Продукти',
    'checkout.summary.delivery': 'Доставка',
    'checkout.summary.free': 'Безплатно',
    'checkout.summary.total': 'Общо за плащане',
    'checkout.actions.cancel': 'Откажи',
    'checkout.actions.prescriptionContinue': 'Продължи към доставка',
    'checkout.actions.submit': 'Завърши поръчката',
    'checkout.actions.continue': 'Продължи',
    'checkout.actions.confirmCard': 'Потвърди и плати с карта',
    'checkout.actions.back': 'Назад',
    'checkout.validation.noItems': 'Добавете продукти, за да завършите поръчката.',
    'checkout.validation.missingSession': 'Моля, влезте отново, за да продължите.',
    'checkout.validation.prescriptionRequired': 'Моля, въведете ЕГН и номер на рецепта.',
    'checkout.validation.personalId': 'ЕГН трябва да съдържа 10 цифри.',
    'checkout.error.generic': 'Възникна грешка при създаването на поръчката.',
    'checkout.success.title': 'Поръчката е приета!',
    'checkout.success.message': 'Ще ви уведомим, когато започнем обработката.',
    'checkout.success.hint': 'Проследявайте всички поръчки в секцията „Моите поръчки“.',
    'checkout.success.close': 'Затвори',

    // AI Assistant
    'ai.title': 'AI Асистент',
    'ai.subtitle': 'Винаги готов да помогне',
    'ai.placeholder': 'Задайте въпрос за лекарство...',
    'ai.thinking': 'Обмислям отговора...',
    'ai.disclaimer': '⚠️ Това е общa информация. Консултирайте се с лекар.',
    'ai.quickQuestion1': 'Как се взима парацетамол?',
    'ai.quickQuestion2': 'Странични ефекти на ибупрофен?',
    'ai.quickQuestion3': 'Витамин C дозировка?',

    // Auth
    'auth.login': 'Вход',
    'auth.loginSubtitle': 'Влезте в профила си',
    'auth.register': 'Регистрация',
    'auth.registerSubtitle': 'Създайте нов акаунт',
    'auth.email': 'Имейл адрес',
    'auth.password': 'Парола',
    'auth.confirmPassword': 'Потвърдете паролата',
    'auth.fullName': 'Пълно име',
    'auth.firstName': 'Име',
    'auth.lastName': 'Фамилия',
    'auth.phone': 'Телефон',
    'auth.address': 'Адрес',
    'auth.age': 'Години',
    'auth.gender': 'Пол',
    'auth.male': 'Мъж',
    'auth.female': 'Жена',
    'auth.other': 'Друг',
    'auth.rememberMe': 'Запомни ме',
    'auth.forgotPassword': 'Забравена парола?',
    'auth.loginButton': 'Влез',
    'auth.registerButton': 'Регистрирай се',
    'auth.loggingIn': 'Влизане...',
    'auth.registering': 'Регистриране...',
    'auth.noAccount': 'Нямате акаунт?',
    'auth.haveAccount': 'Вече имате акаунт?',
    'auth.loginHere': 'Влезте тук',
    'auth.registerHere': 'Регистрирайте се',
    'auth.admin': 'Админ',
    'auth.customers': 'Клиенти',
    'auth.user': 'Потребител',
    'auth.required': 'Задължително поле',
    'auth.passwordsNotMatch': 'Паролите не съвпадат',
    'auth.loginError': 'Грешка при вход',
    'auth.registerError': 'Грешка при регистрация',
    'auth.networkError': 'Мрежова грешка',
    'auth.loginSuccess': 'Успешен вход',
    'auth.registerSuccess': 'Регистрацията е успешна! Можете да влезете в профила си.',
    'auth.twoFactorTitle': 'Двуфакторна верификация',
    'auth.twoFactorSubtitle': 'Въведете кода, изпратен на вашия имейл',
    'auth.twoFactorCodeLabel': 'Код за потвърждение',
    'auth.twoFactorCodePlaceholder': 'Напр. 123456',
    'auth.twoFactorSubmit': 'Потвърди кода',
    'auth.twoFactorChecking': 'Проверка...',
    'auth.twoFactorBack': 'Върни се към входа',
    'auth.twoFactorResend': 'Изпрати нов код',
    'auth.twoFactorResending': 'Изпращане...',
    'auth.twoFactorInvalid': 'Невалиден код за верификация',
    'auth.twoFactorResent': 'Изпратихме нов код за потвърждение.',
    'auth.twoFactorResendError': 'Грешка при изпращане на нов код',
    'auth.twoFactorSentTo': 'Кодът беше изпратен до',
    'auth.twoFactorExpiresAt': 'Кодът е валиден до',

    // Profile Settings
    'profile.title': 'Настройки на профила',
    'profile.subtitle': 'Актуализирайте своята основна информация и контакти.',
    'profile.email': 'Имейл адрес',
    'profile.readonlyEmail': 'Имейл адресът не може да бъде променян.',
    'profile.adminBadge': 'Администратор',
    'profile.staffBadge': 'Служител',
    'profile.fullName': 'Пълно име',
    'profile.fullNamePlaceholder': 'Иван Иванов',
    'profile.phoneNumber': 'Телефон',
    'profile.phonePlaceholder': '+359 88 123 4567',
    'profile.address': 'Адрес',
    'profile.addressPlaceholder': 'гр. София, ул. „Пример“ 1',
    'profile.reset': 'Възстанови',
    'profile.save': 'Запази промените',
    'profile.saving': 'Запазване...',
    'profile.success': 'Профилът беше обновен успешно.',
    'profile.error': 'Възникна грешка при обновяване на профила.',
    'profile.notAuthenticated': 'За да редактирате профила си, трябва да влезете.',

    // Orders
    'orders.modal.title': 'Моите поръчки',
    'orders.modal.subtitle': 'Проследявайте статуса и детайлите на последните си поръчки.',
    'orders.loading': 'Зареждане на поръчките...',
    'orders.actions.retry': 'Опитай отново',
    'orders.actions.refresh': 'Обнови',
    'orders.errors.noSession': 'Няма активна сесия. Моля, влезте отново.',
    'orders.errors.fetchFailed': 'Неуспешно зареждане на поръчките.',
    'orders.errors.notAuthenticated': 'За да видите поръчките си, трябва да влезете.',
    'orders.empty.title': 'Все още нямате поръчки',
    'orders.empty.subtitle': 'След като направите поръчка, тя ще се появи тук.',
    'orders.status.pending': 'В изчакване',
    'orders.status.confirmed': 'Потвърдена',
    'orders.status.processing': 'Обработва се',
    'orders.status.shipped': 'Изпратена',
    'orders.status.delivered': 'Доставена',
    'orders.status.cancelled': 'Отказана',
    'orders.detail.orderNumber': 'Номер на поръчка',
    'orders.detail.paymentMethod': 'Метод на плащане',
    'orders.detail.total': 'Обща сума',
    'orders.detail.items': 'Продукти в поръчката',
    'orders.detail.placedOn': 'Поръчана на {date}',
    'orders.detail.deliveryStatus': 'Статус на доставката',

    // Admin Panel
    'admin.panel.title': 'Администраторски панел',
    'admin.panel.subtitle': 'Управлявайте потребителите и техните права',
    'admin.panel.description': 'Вижте списъка с потребители, редактирайте данни и контролирайте достъпа до платформата.',
    'admin.panel.staffTitle': 'Служителски панел',
    'admin.panel.staffSubtitle': 'Следете клиентските профили и поръчки',
    'admin.panel.staffDescription':
      'Обработвайте поръчки, актуализирайте клиентски данни и публикувайте новини за аптеката.',
    'admin.loading': 'Зареждане на админ панела...',
    'admin.panel.tabs.users': 'Потребители',
    'admin.panel.tabs.permissions': 'Права',
    'admin.panel.tabs.orders': 'Поръчки',
    'admin.panel.tabs.products': 'Каталог',
    'admin.panel.tabs.news': 'Новини',
    'admin.features.sectionTitle': 'Функции на платформата',
    'admin.features.prescriptionTitle': 'Рецептурни услуги',
    'admin.features.prescriptionDescription':
      'Контролирайте достъпа до продукти с рецепта и подаването на е-рецепти.',
    'admin.features.prescriptionStatusEnabled':
      'Потребителите виждат продуктите с рецепта и могат да завършват е-рецепти.',
    'admin.features.prescriptionStatusDisabled':
      'Продуктите с рецепта и е-рецепциите са скрити за всички потребители.',
    'admin.features.prescriptionToggle': 'Управление на рецептурните услуги',
    'admin.features.prescriptionEnabled': 'Вкл.',
    'admin.features.prescriptionDisabled': 'Изкл.',
    'admin.users.searchLabel': 'Търсене на потребители',
    'admin.users.searchPlaceholder': 'Име, имейл или телефон...',
    'admin.users.errors.noSession': 'Не е намерен валиден админ токен. Влезте отново.',
    'admin.users.errors.fetchFailed': 'Неуспешно зареждане на потребителите.',
    'admin.users.errors.saveFailed': 'Неуспешно запазване на промените.',
    'admin.users.errors.staffForbidden': 'Нямате права да редактирате този потребител.',
    'admin.users.retry': 'Опитайте отново',
    'admin.users.badges.admin': 'Администратор',
    'admin.users.badges.staff': 'Служител',
    'admin.users.badges.deactivated': 'Деактивиран',
    'admin.users.badges.active': 'Активен',
    'admin.users.empty': 'Няма намерени потребители.',
    'admin.users.unknownName': 'Няма име',
    'admin.users.memberSince': 'Член от {date}',
    'admin.users.saveSuccess': 'Потребителят е обновен успешно.',
    'admin.users.restrictedNotice':
      'Можете да редактирате само стандартни потребители. Администраторите и служителите са защитени.',
    'admin.users.permissions.title': 'Права и статус',
    'admin.users.permissions.admin': 'Администраторски права',
    'admin.users.permissions.deactivate': 'Маркирай като деактивиран',
    'admin.users.permissions.selfWarning': 'Внимание: променяте собствения си акаунт. Не премахвайте администраторските права, ако се нуждаете от достъп.',
    'admin.permissions.instructions': 'Изберете нивото на достъп за избрания профил. Служителите могат да обработват поръчки и да следят заявки, но нямат достъп до всички системни настройки.',
    'admin.permissions.sectionTitle': 'Управление на достъпа',
    'admin.permissions.admin': 'Пълен администраторски достъп',
    'admin.permissions.staff': 'Оперативен достъп (служител)',
    'admin.permissions.manageProducts': 'Управление на каталога',
    'admin.permissions.deactivate': 'Маркирай акаунта като деактивиран',
    'admin.permissions.save': 'Запази правата',
    'admin.permissions.saving': 'Запазване на правата...',
    'admin.users.fields.email': 'Имейл',
    'admin.users.fields.fullName': 'Пълно име',
    'admin.users.fields.fullNamePlaceholder': 'Име и фамилия',
    'admin.users.fields.phone': 'Телефон',
    'admin.users.fields.phonePlaceholder': 'Мобилен телефон',
    'admin.users.fields.address': 'Адрес',
    'admin.users.fields.addressPlaceholder': 'Адрес за доставка',
    'admin.users.actions.reset': 'Отмени промените',
    'admin.users.actions.refresh': 'Презареди',
    'admin.users.actions.saving': 'Запазване...',
    'admin.users.actions.save': 'Запази',
    'admin.users.noSelection': 'Изберете потребител от списъка, за да редактирате неговите данни.',

    'admin.orders.title': 'Всички поръчки',
    'admin.orders.subtitle': 'Следете поръчките от всички потребители в платформата.',
    'admin.orders.count': 'Поръчки: {count}',
    'admin.orders.refresh': 'Обнови',
    'admin.orders.loading': 'Зареждане на поръчките...',
    'admin.orders.retry': 'Опитай отново',
    'admin.orders.empty': 'Няма намерени поръчки.',
    'admin.orders.customer': 'Клиент',
    'admin.orders.unknownCustomer': 'Неизвестен клиент',
    'admin.orders.summary.total': 'Общо (с доставка)',
    'admin.orders.actions.title': 'Статус на поръчката',
    'admin.orders.actions.pending': 'Маркирай като чакаща',
    'admin.orders.actions.confirm': 'Потвърди',
    'admin.orders.actions.process': 'Започни обработка',
    'admin.orders.actions.ship': 'Изпрати',
    'admin.orders.actions.deliver': 'Достави',
    'admin.orders.actions.cancel': 'Откажи',
    'admin.orders.status.updated': 'Статусът на поръчката е обновен.',
    'admin.orders.errors.noSession': 'Няма активна сесия. Моля, влезте отново.',
    'admin.orders.errors.fetchFailed': 'Неуспешно зареждане на поръчките.',
    'admin.orders.errors.updateFailed': 'Неуспешно обновяване на статуса на поръчката.',

    'admin.products.title': 'Продуктов каталог',
    'admin.products.subtitle': 'Добавяйте, редактирайте и следете артикулите в магазина.',
    'admin.products.count': 'Продукти: {count}',
    'admin.products.searchLabel': 'Търсене в каталога',
    'admin.products.searchPlaceholder': 'Име, производител или описание...',
    'admin.products.empty': 'Няма намерени артикули.',
    'admin.products.unknownCategory': 'Без категория',
    'admin.products.readOnlyNotice': 'Преглеждате каталога в режим само за четене.',
    'admin.products.labels.promo': 'Промоция',
    'admin.products.actions.new': 'Нов артикул',
    'admin.products.actions.reset': 'Върни промените',
    'admin.products.actions.save': 'Запази',
    'admin.products.actions.create': 'Създай',
    'admin.products.actions.delete': 'Изтрий',
    'admin.products.actions.confirmDelete': 'Изтрий артикула',
    'admin.products.actions.cancelDelete': 'Откажи',
    'admin.products.actions.saving': 'Запазване...',
    'admin.products.form.createTitle': 'Нов артикул',
    'admin.products.form.createSubtitle': 'Въведете информацията и запазете, за да добавите артикул.',
    'admin.products.form.editTitle': 'Редакция на артикул',
    'admin.products.form.editSubtitle': 'Актуализирайте детайлите и запазете промените.',
    'admin.products.form.section.details': 'Основна информация',
    'admin.products.form.section.detailsSubtitle': 'Име, описание, цена и наличности.',
    'admin.products.form.section.composition': 'Състав и дозировка',
    'admin.products.form.section.compositionSubtitle': 'Активни съставки, дозировка и производител.',
    'admin.products.form.section.promotion': 'Промоционални условия',
    'admin.products.form.section.promotionSubtitle': 'Активирайте, ако продуктът има текуща промоция.',
    'admin.products.form.fields.nameBg': 'Име (BG)',
    'admin.products.form.fields.nameEn': 'Име (EN)',
    'admin.products.form.fields.descriptionBg': 'Описание (BG)',
    'admin.products.form.fields.descriptionEn': 'Описание (EN)',
    'admin.products.form.fields.price': 'Цена (€)',
    'admin.products.form.fields.stock': 'Наличност',
    'admin.products.form.fields.category': 'Категория',
    'admin.products.form.fields.categoryPlaceholder': 'Изберете категория',
    'admin.products.form.fields.imageUrl': 'URL на изображение',
    'admin.products.form.fields.requiresPrescription': 'Изисква рецепта',
    'admin.products.form.fields.activeIngredientBg': 'Активна съставка (BG)',
    'admin.products.form.fields.activeIngredientEn': 'Активна съставка (EN)',
    'admin.products.form.fields.dosageBg': 'Дозировка (BG)',
    'admin.products.form.fields.dosageEn': 'Дозировка (EN)',
    'admin.products.form.fields.manufacturerBg': 'Производител (BG)',
    'admin.products.form.fields.manufacturerEn': 'Производител (EN)',
    'admin.products.form.fields.enablePromotion': 'Активирай промоция',
    'admin.products.form.fields.promotionId': 'Идентификатор на промоцията',
    'admin.products.form.fields.promotionTitleBg': 'Заглавие (BG)',
    'admin.products.form.fields.promotionTitleEn': 'Заглавие (EN)',
    'admin.products.form.fields.promotionPrice': 'Промо цена (€)',
    'admin.products.form.fields.promotionDiscount': 'Отстъпка (%)',
    'admin.products.form.fields.promotionValidUntil': 'Валидна до',
    'admin.products.form.fields.promotionDescriptionBg': 'Описание (BG)',
    'admin.products.form.fields.promotionDescriptionEn': 'Описание (EN)',
    'admin.products.form.fields.promotionBadge': 'Цвят на значката',
    'admin.products.form.fields.promotionBadgePlaceholder': 'Без значка',
    'admin.products.form.fields.badge.emerald': 'Зелена',
    'admin.products.form.fields.badge.blue': 'Синя',
    'admin.products.form.fields.badge.purple': 'Лилава',
    'admin.products.form.fields.badge.orange': 'Оранжева',
    'admin.products.form.fields.badge.pink': 'Розова',
    'admin.products.errors.listTitle': 'Проверете следните полета:',
    'admin.products.errors.name': 'Въведете име на български.',
    'admin.products.errors.nameEn': 'Въведете име на английски.',
    'admin.products.errors.price': 'Въведете валидна цена по-голяма от нула.',
    'admin.products.errors.stock': 'Наличността не може да е отрицателна.',
    'admin.products.errors.category': 'Изберете категория.',
    'admin.products.errors.imageUrl': 'Добавете URL на изображението.',
    'admin.products.errors.promotionTitle': 'Въведете заглавие на промоцията на български.',
    'admin.products.errors.promotionTitleEn': 'Въведете заглавие на промоцията на английски.',
    'admin.products.errors.promoPrice': 'Въведете валидна промоционална цена.',
    'admin.products.errors.promoPriceCompare': 'Промоционалната цена трябва да е по-ниска от стандартната.',
    'admin.products.errors.discount': 'Отстъпката трябва да е между 0 и 100%.',
    'admin.products.errors.general': 'Моля, прегледайте отбелязаните полета.',
    'admin.products.delete.title': 'Изтриване на артикул',
    'admin.products.delete.description': 'Сигурни ли сте, че искате да изтриете „{name}“?',
    'admin.products.messages.created': 'Артикулът беше създаден успешно.',
    'admin.products.messages.updated': 'Артикулът беше обновен успешно.',
    'admin.products.messages.deleted': 'Артикулът беше изтрит.',

    'admin.news.listTitle': 'Публикувани новини',
    'admin.news.listSubtitle': 'Преглеждайте последните публикации и техните корици.',
    'admin.news.empty': 'Все още няма добавени статии.',
    'admin.news.article.author': 'Автор: {author}',
    'admin.news.editTitle': 'Редактиране на статия',
    'admin.news.editSubtitle': 'Коригирайте съдържанието и запазете промените.',
    'admin.news.createTitle': 'Създаване на нова статия',
    'admin.news.createSubtitle': 'Попълнете информацията и добавете публикацията към блога.',
    'admin.news.messages.created': 'Новината беше създадена успешно.',
    'admin.news.messages.updated': 'Новината беше обновена успешно.',
    'admin.news.messages.deleted': 'Новината беше изтрита.',
    'admin.news.messages.imageGenerated': 'Генерирахме иконка за тази новина.',
    'admin.news.actions.new': 'Нова статия',
    'admin.news.actions.edit': 'Редактирай',
    'admin.news.actions.delete': 'Изтрий',
    'admin.news.actions.editing': 'В режим на редакция',
    'admin.news.actions.openForEditing': 'Отвори „{title}“ за редакция',
    'admin.news.actions.cancelEdit': 'Откажи редакцията',
    'admin.news.errors.listTitle': 'Проверете следните полета:',
    'admin.news.errors.general': 'Моля, коригирайте отбелязаните полета.',
    'admin.news.errors.title': 'Въведете заглавие на български.',
    'admin.news.errors.titleEn': 'Въведете заглавие на английски.',
    'admin.news.errors.excerpt': 'Добавете кратко резюме на български.',
    'admin.news.errors.excerptEn': 'Добавете кратко резюме на английски.',
    'admin.news.errors.content': 'Въведете съдържание на български.',
    'admin.news.errors.contentEn': 'Въведете съдържание на английски.',
    'admin.news.errors.category': 'Добавете категория на български.',
    'admin.news.errors.categoryEn': 'Добавете категория на английски.',
    'admin.news.errors.author': 'Посочете автор на статията.',
    'admin.news.errors.imageUrl': 'Добавете изображение или генерирайте автоматично.',
    'admin.news.errors.publishedAt': 'Изберете валидна дата на публикуване.',
    'admin.news.errors.readTime': 'Въведете време за четене (минимум 1 минута).',
    'admin.news.errors.readTimeRange': 'Времето за четене трябва да е до 60 минути.',
    'admin.news.form.identifierLabel': 'Идентификатор (по избор)',
    'admin.news.form.identifierPlaceholder': 'напр. winter-immunity-2025',
    'admin.news.form.identifierHelp': 'Ако оставите празно, системата ще създаде автоматичен идентификатор.',
    'admin.news.form.titleBg': 'Заглавие (BG)',
    'admin.news.form.titleEn': 'Заглавие (EN)',
    'admin.news.form.excerptBg': 'Резюме (BG)',
    'admin.news.form.excerptEn': 'Резюме (EN)',
    'admin.news.form.contentBg': 'Съдържание (BG)',
    'admin.news.form.contentEn': 'Съдържание (EN)',
    'admin.news.form.categoryBg': 'Категория (BG)',
    'admin.news.form.categoryEn': 'Категория (EN)',
    'admin.news.form.author': 'Автор',
    'admin.news.form.imageUrl': 'URL на изображение',
    'admin.news.form.imageUrlHelp': 'Използвайте собствена снимка или натиснете „Генерирай“, за да създадете графика.',
    'admin.news.form.generateImage': 'Генерирай',
    'admin.news.form.generatedTitleFallback': 'AIPharm Insight',
    'admin.news.form.generatedCategoryFallback': 'Pharmacy Updates',
    'admin.news.form.publishedAt': 'Дата на публикуване',
    'admin.news.form.readTime': 'Време за четене (минути)',
    'admin.news.form.reset': 'Изчисти формата',
    'admin.news.form.resetEditing': 'Върни оригинала',
    'admin.news.form.submit': 'Публикувай статия',
    'admin.news.form.submitUpdate': 'Запази промените',
    'admin.news.form.submitting': 'Публикуване...',
    'admin.news.delete.title': 'Потвърждение за изтриване',
    'admin.news.delete.description': 'Сигурни ли сте, че искате да изтриете „{title}“?',
    'admin.news.delete.confirm': 'Да, изтрий',
    'admin.news.delete.cancel': 'Отказ',

    // Footer
    'footer.title': 'AIPHARM+',
    'footer.description': 'Качествени лекарства с AI консултации и бърза доставка.',
    'footer.version': 'Версия {version}',
    'footer.quickLinks': 'Бързи връзки',
    'footer.aboutUs': 'За нас',
    'footer.products': 'Продукти',
    'footer.services': 'Услуги',
    'footer.contacts': 'Контакти',
    'footer.promotions': 'Промоции',
    'footer.news': 'Новини',
    'footer.faq': 'Често задавани въпроси',
    'footer.contactsTitle': 'Контакти',
    'footer.workingHours': 'Работно време',
    'footer.workingHoursText': 'Пон-Пет: 8:00 - 22:00\nСъб-Нед: 9:00 - 20:00',
    'footer.copyright': '© 2025 AIPHARM+. Всички права запазени.',
    'footer.privacy': 'Политика за поверителност',
    'footer.terms': 'Условия за ползване',
    'footer.cookies': 'Бисквитки',
    'footer.feedbackTitle': 'Споделете мнението си',
    'footer.feedbackDescription': 'Вашата обратна връзка ни помага да подобряваме платформата и услугите на AIPHARM+. Споделете какво мислите за сайта и проекта.',
    'footer.ratingLabel': 'Оценка',
    'footer.starsLabel': 'звезди',
    'footer.messageLabel': 'Отзив',
    'footer.messagePlaceholder': 'Опишете вашето впечатление, какво харесвате и какво можем да подобрим...',
    'footer.feedbackPrivacy': 'Мнението ви ще бъде изпратено по имейл до екипа на AIPHARM+',
    'footer.submitButton': 'Изпрати по имейл',
    'footer.feedbackEmailSubject': 'Обратна връзка за AIPHARM+',

    // Common
    'common.loading': 'Зареждане...',
    'common.error': 'Грешка',
    'common.success': 'Успех',
    'common.cancel': 'Отказ',
    'common.save': 'Запази',
    'common.delete': 'Изтрий',
    'common.edit': 'Редактирай',
    'common.close': 'Затвори',
    'common.back': 'Назад',
    'common.next': 'Напред',
    'common.previous': 'Предишна',
    'common.search': 'Търсене',
    'common.filter': 'Филтър',
    'common.sort': 'Сортиране',
    'common.price': 'Цена',
    'common.quantity': 'Количество',
    'common.total': 'Общо',
    'common.currency': '€',

    // About Us
    'about.description': 'AIPHARM+ е водеща дигитална аптека в България, която съчетава традиционната фармацевтична грижа с най-новите AI технологии.',
    'about.mission': 'Нашата мисия',
    'about.missionText': 'Да предоставяме качествени лекарства и здравни продукти с персонализирани AI консултации, осигурявайки достъпна и надеждна здравна грижа за всеки.',
    'about.vision': 'Нашата визия',
    'about.visionText': 'Да бъдем най-доверената дигитална аптека в България, революционизирайки начина, по който хората получават медицински съвети и лекарства.',
    'about.quality': 'Качество',
    'about.qualityText': 'Всички наши продукти са сертифицирани и одобрени от БЛС.',
    'about.speed': 'Бързина',
    'about.speedText': 'Експресна доставка до 2 часа в София и до 24 часа в цялата страна.',
    'about.care': 'Грижа',
    'about.careText': '24/7 AI асистент и професионални фармацевти на ваше разположение.',
    'about.clients': 'Доволни клиенти',
    'about.products': 'Продукта в наличност',
    'about.experience': 'Години опит',
    'about.support': 'Поддръжка',

    // Services
    'services.pageTitle': 'Нашите услуги',
    'services.pageDescription': 'Комбинираме дигитални иновации с професионална фармацевтична грижа.',
    'services.aiConsultationsTitle': 'AI здравни консултации',
    'services.aiConsultationsDescription': 'Виртуален асистент предоставя доказателствени препоръки и проследява вашите симптоми.',
    'services.aiConsultationsFeature1': 'Персонализирани препоръки за лекарства',
    'services.aiConsultationsFeature2': 'Анализ на симптоми в реално време',
    'services.aiConsultationsFeature3': 'Ескалация към фармацевт при нужда',
    'services.telepharmacyTitle': 'Телефармация с експерти',
    'services.telepharmacyDescription': 'Лицензирани фармацевти, които ви подкрепят дистанционно.',
    'services.telepharmacyFeature1': 'Видео консултации и чат на живо',
    'services.telepharmacyFeature2': 'Проверка за взаимодействия на лекарства',
    'services.telepharmacyFeature3': 'Проследяване на терапиите и контролни обаждания',
    'services.deliveryTitle': 'Логистика и доставка',
    'services.deliveryDescription': 'Собствена мрежа за бърза и сигурна доставка в цялата страна.',
    'services.deliveryFeature1': 'Експресни доставки до 2 часа в София',
    'services.deliveryFeature2': 'Проследяване на пратката в реално време',
    'services.deliveryFeature3': 'Температурно контролиран транспорт',
    'services.valueTitle': 'Защо да изберете AIPHARM+',
    'services.valueSubtitle': 'Съчетаваме безопасност, експертиза и удобство за нашите клиенти.',
    'services.valuePatients': 'Грижа за пациента',
    'services.valuePatientsDesc': 'Индивидуални планове и напомняния за прием на лекарства.',
    'services.valueData': 'Сигурност на данните',
    'services.valueDataDesc': 'Напълно криптирана платформа с постоянен мониторинг.',
    'services.valueSupport': 'Поддръжка 24/7',
    'services.valueSupportDesc': 'Експерти на разположение по телефон, чат и имейл.',
    'services.ctaTitle': 'Нуждаете се от персонална консултация?',
    'services.ctaDescription': 'Свържете се с нас и ще ви насочим към най-подходящата услуга.',
    'services.ctaButton': 'Свържете се с експерт',

    // Contacts
    'contacts.description': 'Свържете се с нас по всяко време. Нашият екип е готов да ви помогне с всички въпроси.',
    'contacts.info': 'Информация за контакт',
    'contacts.phone': 'Телефон',
    'contacts.email': 'Имейл',
    'contacts.address': 'Адрес',
    'contacts.emergency': 'Спешни случаи',
    'contacts.emergencyText': 'При медицински спешни случаи, моля обърнете се към спешните служби.',
    'contacts.emergencyNumber': 'Спешен номер',
    'contacts.sendMessage': 'Изпратете съобщение',
    'contacts.firstName': 'Име',
    'contacts.lastName': 'Фамилия',
    'contacts.subject': 'Тема',
    'contacts.message': 'Съобщение',
    'contacts.send': 'Изпрати',
    'contacts.firstNamePlaceholder': 'Вашето име',
    'contacts.lastNamePlaceholder': 'Вашата фамилия',
    'contacts.emailPlaceholder': 'your@email.com',
    'contacts.subjectPlaceholder': 'Тема на съобщението',
    'contacts.messagePlaceholder': 'Напишете вашето съобщение тук...',

    // Promotions
    'promotions.description': 'Открийте нашите актуални промоции и спестете при покупката на лекарства и здравни продукти.',
    'promotions.currentCount': '{count} активни оферти',
    'promotions.activeOffers': 'Активни оферти',
    'promotions.averageDiscount': 'Средна отстъпка',
    'promotions.highestDiscount': 'Най-висока отстъпка: {value}%',
    'promotions.estimatedSavings': 'Потенциални спестявания',
    'promotions.limitedStock': 'Офертите са валидни до изчерпване на количествата',
    'promotions.noActive': 'В момента няма активни промоции.',
    'promotions.freeDelivery': 'Безплатна доставка',
    'promotions.freeDeliveryDesc': 'Безплатна доставка за всички поръчки над €25 в цялата страна.',
    'promotions.vitamins20': '20% отстъпка на витамини',
    'promotions.vitamins20Desc': 'Специална промоция на всички витамини и хранителни добавки.',
    'promotions.firstOrder': 'Първа поръчка',
    'promotions.firstOrderDesc': '15% отстъпка за нови клиенти при първата им поръчка.',
    'promotions.loyaltyProgram': 'Програма за лоялност',
    'promotions.loyaltyProgramDesc': 'Събирайте точки с всяка покупка и получавайте отстъпки.',
    'promotions.free': 'Безплатно',
    'promotions.points': 'Точки',
    'promotions.permanent': 'Постоянна',
    'promotions.discount': 'отстъпка',
    'promotions.validUntil': 'Валидна до',
    'promotions.useNow': 'Използвай сега',
    'promotions.howToUse': 'Как да използвате промоциите',
    'promotions.step1': 'Изберете продукти',
    'promotions.step1Desc': 'Добавете желаните продукти в количката си.',
    'promotions.step2': 'Приложете код',
    'promotions.step2Desc': 'Въведете промо кода при финализиране.',
    'promotions.step3': 'Спестете пари',
    'promotions.step3Desc': 'Получете отстъпката и завършете поръчката.',

    // News
    'news.title': 'Новини и полезни съвети',
    'news.subtitle': 'Последни тенденции, препоръки и анализи от нашите фармацевти и специалисти.',
    'news.latest': 'Последни публикации',
    'news.readMore': 'Прочетете повече',
    'news.showLess': 'Покажи по-малко',
    'news.readTime': '{minutes} мин четене',
    'news.published': 'Публикувано на',
    'news.authorBy': 'Автор:',

    // FAQ
    'faq.description': 'Намерете отговори на най-често задаваните въпроси за нашите услуги.',
    'faq.searchPlaceholder': 'Търсете въпрос...',
    'faq.noResults': 'Няма намерени резултати',
    'faq.tryDifferent': 'Опитайте с различни ключови думи.',
    'faq.stillNeedHelp': 'Все още имате нужда от помощ?',
    'faq.contactSupport': 'Нашият екип за поддръжка е готов да ви помогне.',
    'faq.callUs': 'Обадете се',
    'faq.emailUs': 'Изпратете имейл',
    'faq.q1': 'Колко време отнема доставката?',
    'faq.a1': 'Доставката в София е до 2 часа, а в останалата част на страната - до 24 часа. За спешни случаи предлагаме експресна доставка.',
    'faq.q2': 'Какви методи за плащане приемате?',
    'faq.a2': 'Приемаме плащания с дебитни и кредитни карти, банков превод, както и плащане при доставка (наложен платеж).',
    'faq.q3': 'Нужна ли е рецепта за всички лекарства?',
    'faq.a3': 'Не, много лекарства са безрецептурни. Продуктите, които изискват рецепта, са ясно обозначени в сайта.',
    'faq.q4': 'Как работи AI асистентът?',
    'faq.a4': 'Нашият AI асистент предоставя обща информация за лекарствата. Винаги се консултирайте с лекар за персонализиран съвет.',
    'faq.q5': 'Мога ли да върна продукт?',
    'faq.a5': 'Да, можете да върнете неотворени продукти в рамките на 14 дни от покупката, съгласно закона за защита на потребителите.',
    'faq.q6': 'Как да създам акаунт?',
    'faq.a6': 'Кликнете на "Регистрация" в горния десен ъгъл и попълнете необходимата информация. Акаунтът ви ще бъде активиран веднага.',
    'faq.q7': 'Доставяте ли извън София?',
    'faq.a7': 'Да, доставяме в цялата страна. Доставката извън София отнема до 24 часа.',
    'faq.q8': 'Сигурни ли са личните ми данни?',
    'faq.a8': 'Да, използваме най-високите стандарти за сигурност и криптиране на данните. Вашата информация е напълно защитена.'
  },
  en: {
    // Header
    'header.title': 'AIPHARM+',
    'header.subtitle': 'AI pharmacy & assistant',
    'header.search': 'Search medicines, vitamins, cosmetics...',
    'header.phone': '+359 2 123 4567',
    'header.freeDelivery': 'Free delivery over €25',
    'header.myProfile': 'My Profile',
    'header.myOrders': 'My Orders',
    'header.help': 'Help',
    'header.login': 'Login',
    'header.register': 'Register',
    'header.logout': 'Logout',
    'header.settings': 'Profile Settings',
    'header.adminPanel': 'Admin Panel',
    'header.staffPanel': 'Staff Panel',
    'header.hello': 'Hello',
    'header.administrator': 'Administrator',
    'header.staffMember': 'Staff member',

    // Navigation
    'navigation.categories': 'Categories',
    'navigation.products': 'Products',
    'navigation.promotions': 'Promotions',
    'navigation.news': 'News',

    // Hero Section
    'hero.title': 'AIPHARM+',
    'hero.description': 'Quality medicines with AI consultations and fast delivery',
    'hero.certifiedQuality': 'Certified Quality',
    'hero.support247': '24/7 Support',
    'hero.expressDelivery': 'Express Delivery',
    'hero.qualityAwards': 'Quality Awards',
    'hero.viewProducts': 'View Products',
    'hero.aiAssistant': 'AI Medical Assistant',
    'hero.satisfiedClients': 'Satisfied Clients',
    'hero.productsInStock': 'Products in Stock',
    'hero.professionalCare': 'Professional Care',

    // Home Page
    'home.dateTime.title': 'Current date & time',
    'home.dateTime.localDate': 'Date',
    'home.dateTime.localTime': 'Time',
    'home.promotionsTitle': 'Current promotions',
    'home.promotionsSubtitle': 'Special limited-time offers selected for your wellbeing.',
    'home.promotionsViewAll': 'View all promotions',
    'home.promotionsEmpty': 'There are no active promotions right now. Check back soon.',

    // Categories
    'categories.title': 'Categories',
    'categories.subtitle': 'Explore our main categories and find the right treatments.',
    'categories.previewSubtitle': 'Take a quick look at some of our most popular categories.',
    'categories.viewAll': 'View all categories',
    'categories.viewProducts': 'View products',
    'categories.searchLabel': 'Search categories',
    'categories.searchPlaceholder': 'Filter by name or description...',
    'categories.sortLabel': 'Sort by',
    'categories.sortPopular': 'Most popular',
    'categories.sortAlphabetical': 'Alphabetical',
    'categories.sortProducts': 'Most products',
    'categories.preview': 'Preview',
    'categories.all': 'All',
    'categories.painkillers': 'Painkillers',
    'categories.vitamins': 'Vitamins',
    'categories.coldFlu': 'Cold & Flu',
    'categories.digestive': 'Digestive',
    'categories.skinHair': 'Skin & Hair',
    'categories.children': 'Children Products',

    // Products
    'products.featuredTitle': 'Featured products',
    'products.featuredSubtitle': 'A quick look at some of our most popular picks.',
    'products.resultsFor': 'Results for',
    'products.category': 'Category',
    'products.unknown': 'Unknown',
    'products.allProducts': 'All Products',
    'products.products': 'products',
    'products.noProducts': 'No products found',
    'products.tryDifferent': 'Try different keywords or browse our categories',
    'products.viewAll': 'View all products',
    'products.showLess': 'Show less',
    'products.prescription': 'Prescription',
    'products.activeIngredient': 'Active Ingredient',
    'products.dosage': 'Dosage',
    'products.manufacturer': 'Manufacturer',
    'products.inStock': 'In Stock',
    'products.outOfStock': 'Out of Stock',
    'products.pieces': 'pcs.',
    'products.add': 'Add',
    'products.askAssistant': 'Ask the AI assistant',
    'products.moreInfo': 'More information',
    'products.productDetails': 'Product details',
    'products.descriptionLabel': 'Description',
    'products.prescriptionRequiredLabel': 'Prescription requirement',
    'products.stockStatus': 'Stock status',
    'products.promotionValidUntil': 'Promotion valid until',
    'products.viewDetails': 'View details',
    'products.reviews': 'reviews',
    'products.catalogTitle': 'Product catalog',
    'products.catalogDescription': 'Browse the full range of medicines, supplements, and cosmetics curated by our specialists.',
    'products.categoryOverview': 'Categories & availability',
    'products.categoryOverviewDescription': 'Quick overview of our main categories and available products.',
    'products.totalProductsLabel': 'Total products',
    'products.inCategory': 'In the category',
    'products.filtersTitle': 'Filters',
    'products.filtersSubtitle': 'Fine-tune the catalog to match your needs.',
    'products.searchInCatalog': 'Catalog search',
    'products.searchPlaceholder': 'Search by name, ingredient, or description...',
    'products.priceRange': 'Price range',
    'products.minPrice': 'Min price',
    'products.maxPrice': 'Max price',
    'products.availability': 'Availability',
    'products.availabilityAll': 'All',
    'products.availabilityInStock': 'In stock',
    'products.availabilityOutOfStock': 'Out of stock',
    'products.prescriptionFilter': 'Prescription need',
    'products.requiresPrescription': 'Prescription only',
    'products.overTheCounter': 'Over the counter',
    'products.promotionsOnly': 'Promotions only',
    'products.sortBy': 'Sort by',
    'products.sortPopular': 'Recommended',
    'products.sortPriceLowHigh': 'Price: low to high',
    'products.sortPriceHighLow': 'Price: high to low',
    'products.clearFilters': 'Clear filters',
    'products.moreInfoTitle': 'Additional information',
    'products.moreInfoSubtitle':
      'We will soon add detailed instructions, leaflets, and intake recommendations for every product.',
    'products.moreInfoPlaceholder':
      'This section will host the official leaflet, usage guidance, and important warnings.',
    'products.moreInfoNotFoundTitle': 'Product not found',
    'products.moreInfoNotFoundDescription': 'Please return to the catalog and choose another product.',

    // Cart
    'cart.title': 'Cart',
    'cart.empty': 'Cart is empty',
    'cart.emptyDescription': 'Add products to continue with your order',
    'cart.continueShopping': 'Continue Shopping',
    'cart.remove': 'Remove',
    'cart.total': 'Total',
    'cart.freeDelivery': '✓ Free delivery',
    'cart.loginRequired': 'Log in with your account to complete your order.',
    'cart.regularPrice': 'Regular price',
    'cart.promoPrice': 'Promo price',
    'cart.addForFreeDelivery': 'Add products for €{amount} for free delivery',
    'cart.checkout': 'Checkout',

    // Checkout
    'checkout.title': 'Checkout',
    'checkout.subtitle': 'Enter your delivery and contact details.',
    'checkout.section.prescription': 'Prescription details',
    'checkout.section.personal': 'Personal information',
    'checkout.section.delivery': 'Delivery details',
    'checkout.section.payment': 'Payment method',
    'checkout.section.summary': 'Order summary',
    'checkout.prescription.subtitle': 'For prescription medicines, please provide your national ID and e-prescription number.',
    'checkout.prescription.privacy': 'The information is only used to verify coverage with the NHIF.',
    'checkout.field.fullName': 'Full name',
    'checkout.field.email': 'Email address',
    'checkout.field.phone': 'Phone',
    'checkout.field.personalId': 'Personal ID (EGN)',
    'checkout.field.prescriptionNumber': 'Prescription number',
    'checkout.field.address': 'Address',
    'checkout.field.city': 'City',
    'checkout.field.postalCode': 'Postal code',
    'checkout.field.country': 'Country',
    'checkout.field.notes': 'Order notes',
    'checkout.paymentUnavailable': 'Payments will be enabled in production. Choose a method and finish the order.',
    'checkout.payment.cashOnDelivery': 'Cash on delivery',
    'checkout.payment.card': 'Card',
    'checkout.payment.bankTransfer': 'Bank transfer',
    'checkout.prescription.title': 'ePrescription verification required',
    'checkout.prescription.description':
      'A prescription-only product is in your cart. To continue, enter your personal ID number and the ePrescription code.',
    'checkout.prescription.stepTitle': 'ePrescription',
    'checkout.prescription.stepSubtitle': 'Provide the information from your ePrescription to finalize the order.',
    'checkout.prescription.egn': 'Personal ID number (EGN)',
    'checkout.prescription.code': 'ePrescription code',
    'checkout.prescription.cardOnly': 'Prescription items can only be paid by card.',
    'checkout.summary.subtotal': 'Products',
    'checkout.summary.delivery': 'Delivery',
    'checkout.summary.free': 'Free',
    'checkout.summary.total': 'Total due',
    'checkout.actions.cancel': 'Cancel',
    'checkout.actions.prescriptionContinue': 'Continue to delivery',
    'checkout.actions.submit': 'Place order',
    'checkout.actions.continue': 'Continue',
    'checkout.actions.confirmCard': 'Confirm and pay by card',
    'checkout.actions.back': 'Back',
    'checkout.validation.noItems': 'Add some items to complete the order.',
    'checkout.validation.missingSession': 'Please sign in again to continue.',
    'checkout.validation.prescriptionRequired': 'Please enter your personal ID and prescription number.',
    'checkout.validation.personalId': 'The personal ID must contain exactly 10 digits.',
    'checkout.error.generic': 'Unable to create the order. Please try again.',
    'checkout.success.title': 'Order received!',
    'checkout.success.message': 'We will notify you once we start processing it.',
    'checkout.success.hint': 'You can track all orders from the “My Orders” section.',
    'checkout.success.close': 'Close',

    // AI Assistant
    'ai.title': 'AI Assistant',
    'ai.subtitle': 'Always ready to help',
    'ai.placeholder': 'Ask a question about medicine...',
    'ai.thinking': 'Thinking of an answer...',
    'ai.disclaimer': '⚠️ This is general information. Consult with a doctor.',
    'ai.quickQuestion1': 'How to take paracetamol?',
    'ai.quickQuestion2': 'Ibuprofen side effects?',
    'ai.quickQuestion3': 'Vitamin C dosage?',

    // Auth
    'auth.login': 'Login',
    'auth.loginSubtitle': 'Sign in to your account',
    'auth.register': 'Register',
    'auth.registerSubtitle': 'Create a new account',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.fullName': 'Full Name',
    'auth.firstName': 'First Name',
    'auth.lastName': 'Last Name',
    'auth.phone': 'Phone',
    'auth.address': 'Address',
    'auth.age': 'Age',
    'auth.gender': 'Gender',
    'auth.male': 'Male',
    'auth.female': 'Female',
    'auth.other': 'Other',
    'auth.rememberMe': 'Remember Me',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.loginButton': 'Sign In',
    'auth.registerButton': 'Register',
    'auth.loggingIn': 'Signing in...',
    'auth.registering': 'Registering...',
    'auth.noAccount': "Don't have an account?",
    'auth.haveAccount': 'Already have an account?',
    'auth.loginHere': 'Sign in here',
    'auth.registerHere': 'Register here',
    'auth.admin': 'Admin',
    'auth.customers': 'Customers',
    'auth.user': 'User',
    'auth.required': 'Required field',
    'auth.passwordsNotMatch': 'Passwords do not match',
    'auth.loginError': 'Login error',
    'auth.registerError': 'Registration error',
    'auth.networkError': 'Network error',
    'auth.loginSuccess': 'Login successful',
    'auth.registerSuccess': 'Registration successful! You can now sign in to your account.',
    'auth.twoFactorTitle': 'Two-factor verification',
    'auth.twoFactorSubtitle': 'Enter the code sent to your email',
    'auth.twoFactorCodeLabel': 'Verification code',
    'auth.twoFactorCodePlaceholder': 'e.g. 123456',
    'auth.twoFactorSubmit': 'Confirm code',
    'auth.twoFactorChecking': 'Verifying...',
    'auth.twoFactorBack': 'Back to login',
    'auth.twoFactorResend': 'Send new code',
    'auth.twoFactorResending': 'Sending...',
    'auth.twoFactorInvalid': 'Invalid verification code',
    'auth.twoFactorResent': 'A new verification code has been sent.',
    'auth.twoFactorResendError': 'Could not send a new code',
    'auth.twoFactorSentTo': 'Code sent to',
    'auth.twoFactorExpiresAt': 'Code expires at',

    // Profile Settings
    'profile.title': 'Profile settings',
    'profile.subtitle': 'Update your contact information and personal details.',
    'profile.email': 'Email address',
    'profile.readonlyEmail': 'The email address cannot be changed.',
    'profile.adminBadge': 'Administrator',
    'profile.staffBadge': 'Staff member',
    'profile.fullName': 'Full name',
    'profile.fullNamePlaceholder': 'John Doe',
    'profile.phoneNumber': 'Phone number',
    'profile.phonePlaceholder': '+359 88 123 4567',
    'profile.address': 'Address',
    'profile.addressPlaceholder': 'Sofia, Vitosha Blvd. 25',
    'profile.reset': 'Reset',
    'profile.save': 'Save changes',
    'profile.saving': 'Saving...',
    'profile.success': 'Profile updated successfully.',
    'profile.error': 'Could not update the profile.',
    'profile.notAuthenticated': 'You need to be signed in to edit your profile.',

    // Orders
    'orders.modal.title': 'My orders',
    'orders.modal.subtitle': 'Track the status and details of your recent purchases.',
    'orders.loading': 'Loading orders...',
    'orders.actions.retry': 'Try again',
    'orders.actions.refresh': 'Refresh',
    'orders.errors.noSession': 'No active session found. Please sign in again.',
    'orders.errors.fetchFailed': 'Could not load orders.',
    'orders.errors.notAuthenticated': 'Please sign in to view your orders.',
    'orders.empty.title': 'No orders yet',
    'orders.empty.subtitle': 'Your orders will appear here after you complete a purchase.',
    'orders.status.pending': 'Pending',
    'orders.status.confirmed': 'Confirmed',
    'orders.status.processing': 'Processing',
    'orders.status.shipped': 'Shipped',
    'orders.status.delivered': 'Delivered',
    'orders.status.cancelled': 'Cancelled',
    'orders.detail.orderNumber': 'Order number',
    'orders.detail.paymentMethod': 'Payment method',
    'orders.detail.total': 'Total',
    'orders.detail.items': 'Items',
    'orders.detail.placedOn': 'Placed on {date}',
    'orders.detail.deliveryStatus': 'Delivery status',

    // Admin Panel
    'admin.panel.title': 'Administration',
    'admin.panel.subtitle': 'Manage user accounts and permissions',
    'admin.panel.description': 'Review the registered users, edit their details and control access rights.',
    'admin.panel.staffTitle': 'Staff Panel',
    'admin.panel.staffSubtitle': 'Support customer accounts and orders',
    'admin.panel.staffDescription':
      'Process incoming orders, update customer details and publish pharmacy news.',
    'admin.loading': 'Loading admin workspace...',
    'admin.panel.tabs.users': 'Users',
    'admin.panel.tabs.permissions': 'Permissions',
    'admin.panel.tabs.orders': 'Orders',
    'admin.panel.tabs.products': 'Catalog',
    'admin.panel.tabs.news': 'News',
    'admin.features.sectionTitle': 'Platform features',
    'admin.features.prescriptionTitle': 'Prescription services',
    'admin.features.prescriptionDescription':
      'Control the availability of prescription-only products and e-prescription submissions.',
    'admin.features.prescriptionStatusEnabled':
      'Customers can see prescription-only items and submit e-prescriptions.',
    'admin.features.prescriptionStatusDisabled':
      'Prescription-only products and e-prescriptions are hidden for all customers.',
    'admin.features.prescriptionToggle': 'Manage prescription services',
    'admin.features.prescriptionEnabled': 'On',
    'admin.features.prescriptionDisabled': 'Off',
    'admin.users.searchLabel': 'Search users',
    'admin.users.searchPlaceholder': 'Name, email or phone...',
    'admin.users.errors.noSession': 'Missing admin session. Please sign in again.',
    'admin.users.errors.fetchFailed': 'Unable to load users.',
    'admin.users.errors.saveFailed': 'Unable to save the changes.',
    'admin.users.errors.staffForbidden': 'You are not allowed to edit this account.',
    'admin.users.retry': 'Try again',
    'admin.users.badges.admin': 'Admin',
    'admin.users.badges.staff': 'Staff',
    'admin.users.badges.deactivated': 'Deactivated',
    'admin.users.badges.active': 'Active',
    'admin.users.empty': 'No users found.',
    'admin.users.unknownName': 'No name provided',
    'admin.users.memberSince': 'Member since {date}',
    'admin.users.saveSuccess': 'User updated successfully.',
    'admin.users.restrictedNotice':
      'You can only edit standard customers. Administrators and staff accounts are protected.',
    'admin.users.permissions.title': 'Permissions & status',
    'admin.users.permissions.admin': 'Administrator rights',
    'admin.users.permissions.deactivate': 'Mark as deactivated',
    'admin.users.permissions.selfWarning': 'Warning: you are editing your own account. Do not remove your admin rights unless you are sure.',
    'admin.permissions.instructions': 'Choose the appropriate access level for this account. Staff members can process orders and monitor requests but cannot change critical system settings.',
    'admin.permissions.sectionTitle': 'Access management',
    'admin.permissions.admin': 'Full administrator access',
    'admin.permissions.staff': 'Operational access (staff)',
    'admin.permissions.manageProducts': 'Product catalog management',
    'admin.permissions.deactivate': 'Deactivate this account',
    'admin.permissions.save': 'Save permissions',
    'admin.permissions.saving': 'Saving permissions...',
    'admin.users.fields.email': 'Email',
    'admin.users.fields.fullName': 'Full name',
    'admin.users.fields.fullNamePlaceholder': 'First and last name',
    'admin.users.fields.phone': 'Phone number',
    'admin.users.fields.phonePlaceholder': 'Contact phone',
    'admin.users.fields.address': 'Address',
    'admin.users.fields.addressPlaceholder': 'Delivery address',
    'admin.users.actions.reset': 'Discard changes',
    'admin.users.actions.refresh': 'Refresh',
    'admin.users.actions.saving': 'Saving...',
    'admin.users.actions.save': 'Save',
    'admin.users.noSelection': 'Select a user from the list to edit their details.',

    'admin.orders.title': 'All orders',
    'admin.orders.subtitle': 'Monitor every order placed across the platform.',
    'admin.orders.count': 'Orders: {count}',
    'admin.orders.refresh': 'Refresh',
    'admin.orders.loading': 'Loading orders...',
    'admin.orders.retry': 'Try again',
    'admin.orders.empty': 'No orders found.',
    'admin.orders.customer': 'Customer',
    'admin.orders.unknownCustomer': 'Unknown customer',
    'admin.orders.summary.total': 'Grand total',
    'admin.orders.actions.title': 'Order status',
    'admin.orders.actions.pending': 'Set to pending',
    'admin.orders.actions.confirm': 'Confirm',
    'admin.orders.actions.process': 'Mark processing',
    'admin.orders.actions.ship': 'Mark shipped',
    'admin.orders.actions.deliver': 'Deliver',
    'admin.orders.actions.cancel': 'Cancel order',
    'admin.orders.status.updated': 'Order status updated.',
    'admin.orders.errors.noSession': 'No active session. Please sign in again.',
    'admin.orders.errors.fetchFailed': 'Failed to load orders.',
    'admin.orders.errors.updateFailed': 'Failed to update the order status.',

    'admin.products.title': 'Product catalog',
    'admin.products.subtitle': 'Create, update and monitor every item in the store.',
    'admin.products.count': 'Products: {count}',
    'admin.products.searchLabel': 'Search catalog',
    'admin.products.searchPlaceholder': 'Name, manufacturer or description...',
    'admin.products.empty': 'No products found.',
    'admin.products.unknownCategory': 'Unassigned category',
    'admin.products.readOnlyNotice': 'You have read-only access to the catalog.',
    'admin.products.labels.promo': 'Promotion',
    'admin.products.actions.new': 'New product',
    'admin.products.actions.reset': 'Discard changes',
    'admin.products.actions.save': 'Save changes',
    'admin.products.actions.create': 'Create product',
    'admin.products.actions.delete': 'Delete',
    'admin.products.actions.confirmDelete': 'Delete product',
    'admin.products.actions.cancelDelete': 'Keep product',
    'admin.products.actions.saving': 'Saving...',
    'admin.products.form.createTitle': 'Create product',
    'admin.products.form.createSubtitle': 'Fill in the details below and publish the item.',
    'admin.products.form.editTitle': 'Edit product',
    'admin.products.form.editSubtitle': 'Update the information and save your changes.',
    'admin.products.form.section.details': 'Core information',
    'admin.products.form.section.detailsSubtitle': 'Name, description, price and stock level.',
    'admin.products.form.section.composition': 'Composition & dosage',
    'admin.products.form.section.compositionSubtitle': 'Active ingredients, dosage and manufacturer.',
    'admin.products.form.section.promotion': 'Promotional offer',
    'admin.products.form.section.promotionSubtitle': 'Enable if the product has an active promotion.',
    'admin.products.form.fields.nameBg': 'Name (BG)',
    'admin.products.form.fields.nameEn': 'Name (EN)',
    'admin.products.form.fields.descriptionBg': 'Description (BG)',
    'admin.products.form.fields.descriptionEn': 'Description (EN)',
    'admin.products.form.fields.price': 'Price (€)',
    'admin.products.form.fields.stock': 'Stock quantity',
    'admin.products.form.fields.category': 'Category',
    'admin.products.form.fields.categoryPlaceholder': 'Select a category',
    'admin.products.form.fields.imageUrl': 'Image URL',
    'admin.products.form.fields.requiresPrescription': 'Requires prescription',
    'admin.products.form.fields.activeIngredientBg': 'Active ingredient (BG)',
    'admin.products.form.fields.activeIngredientEn': 'Active ingredient (EN)',
    'admin.products.form.fields.dosageBg': 'Dosage (BG)',
    'admin.products.form.fields.dosageEn': 'Dosage (EN)',
    'admin.products.form.fields.manufacturerBg': 'Manufacturer (BG)',
    'admin.products.form.fields.manufacturerEn': 'Manufacturer (EN)',
    'admin.products.form.fields.enablePromotion': 'Enable promotion',
    'admin.products.form.fields.promotionId': 'Promotion identifier',
    'admin.products.form.fields.promotionTitleBg': 'Title (BG)',
    'admin.products.form.fields.promotionTitleEn': 'Title (EN)',
    'admin.products.form.fields.promotionPrice': 'Promo price (€)',
    'admin.products.form.fields.promotionDiscount': 'Discount (%)',
    'admin.products.form.fields.promotionValidUntil': 'Valid until',
    'admin.products.form.fields.promotionDescriptionBg': 'Description (BG)',
    'admin.products.form.fields.promotionDescriptionEn': 'Description (EN)',
    'admin.products.form.fields.promotionBadge': 'Badge color',
    'admin.products.form.fields.promotionBadgePlaceholder': 'No badge',
    'admin.products.form.fields.badge.emerald': 'Emerald',
    'admin.products.form.fields.badge.blue': 'Blue',
    'admin.products.form.fields.badge.purple': 'Purple',
    'admin.products.form.fields.badge.orange': 'Orange',
    'admin.products.form.fields.badge.pink': 'Pink',
    'admin.products.errors.listTitle': 'Please review the following fields:',
    'admin.products.errors.name': 'Enter a Bulgarian product name.',
    'admin.products.errors.nameEn': 'Enter an English product name.',
    'admin.products.errors.price': 'Enter a valid price greater than zero.',
    'admin.products.errors.stock': 'Stock quantity cannot be negative.',
    'admin.products.errors.category': 'Choose a category.',
    'admin.products.errors.imageUrl': 'Add a product image URL.',
    'admin.products.errors.promotionTitle': 'Add a Bulgarian promotion title.',
    'admin.products.errors.promotionTitleEn': 'Add an English promotion title.',
    'admin.products.errors.promoPrice': 'Enter a valid promotional price.',
    'admin.products.errors.promoPriceCompare': 'The promotional price must be lower than the regular price.',
    'admin.products.errors.discount': 'Discount must be between 0 and 100%.',
    'admin.products.errors.general': 'Fix the highlighted fields before saving.',
    'admin.products.delete.title': 'Delete product',
    'admin.products.delete.description': 'Are you sure you want to delete “{name}”?',
    'admin.products.messages.created': 'The product was created successfully.',
    'admin.products.messages.updated': 'The product was updated successfully.',
    'admin.products.messages.deleted': 'The product was deleted.',

    'admin.news.listTitle': 'Published news',
    'admin.news.listSubtitle': 'Review the latest blog posts and their cover artwork.',
    'admin.news.empty': 'No articles have been added yet.',
    'admin.news.article.author': 'Author: {author}',
    'admin.news.editTitle': 'Edit article',
    'admin.news.editSubtitle': 'Update the content and save your changes.',
    'admin.news.createTitle': 'Create a new article',
    'admin.news.createSubtitle': 'Fill in the details below to publish a new blog post.',
    'admin.news.messages.created': 'The article was created successfully.',
    'admin.news.messages.updated': 'The article was updated successfully.',
    'admin.news.messages.deleted': 'The article was deleted.',
    'admin.news.messages.imageGenerated': 'A cover illustration was generated for this article.',
    'admin.news.actions.new': 'New article',
    'admin.news.actions.edit': 'Edit',
    'admin.news.actions.delete': 'Delete',
    'admin.news.actions.editing': 'Editing',
    'admin.news.actions.openForEditing': 'Open “{title}” for editing',
    'admin.news.actions.cancelEdit': 'Cancel editing',
    'admin.news.errors.listTitle': 'Please review the following fields:',
    'admin.news.errors.general': 'Fix the highlighted fields before publishing.',
    'admin.news.errors.title': 'Enter a Bulgarian title.',
    'admin.news.errors.titleEn': 'Enter an English title.',
    'admin.news.errors.excerpt': 'Provide a Bulgarian excerpt.',
    'admin.news.errors.excerptEn': 'Provide an English excerpt.',
    'admin.news.errors.content': 'Add Bulgarian article content.',
    'admin.news.errors.contentEn': 'Add English article content.',
    'admin.news.errors.category': 'Specify the Bulgarian category.',
    'admin.news.errors.categoryEn': 'Specify the English category.',
    'admin.news.errors.author': 'Set the article author.',
    'admin.news.errors.imageUrl': 'Add or generate a cover image URL.',
    'admin.news.errors.publishedAt': 'Choose a valid publish date.',
    'admin.news.errors.readTime': 'Provide a reading time of at least 1 minute.',
    'admin.news.errors.readTimeRange': 'Reading time must be 60 minutes or less.',
    'admin.news.form.identifierLabel': 'Identifier (optional)',
    'admin.news.form.identifierPlaceholder': 'e.g. winter-immunity-2025',
    'admin.news.form.identifierHelp': 'Leave blank to generate an identifier automatically.',
    'admin.news.form.titleBg': 'Title (BG)',
    'admin.news.form.titleEn': 'Title (EN)',
    'admin.news.form.excerptBg': 'Excerpt (BG)',
    'admin.news.form.excerptEn': 'Excerpt (EN)',
    'admin.news.form.contentBg': 'Content (BG)',
    'admin.news.form.contentEn': 'Content (EN)',
    'admin.news.form.categoryBg': 'Category (BG)',
    'admin.news.form.categoryEn': 'Category (EN)',
    'admin.news.form.author': 'Author',
    'admin.news.form.imageUrl': 'Image URL',
    'admin.news.form.imageUrlHelp': 'Use your own image or press “Generate” to create artwork automatically.',
    'admin.news.form.generateImage': 'Generate',
    'admin.news.form.generatedTitleFallback': 'AIPharm Insight',
    'admin.news.form.generatedCategoryFallback': 'Pharmacy Updates',
    'admin.news.form.publishedAt': 'Publish date',
    'admin.news.form.readTime': 'Reading time (minutes)',
    'admin.news.form.reset': 'Reset form',
    'admin.news.form.resetEditing': 'Reset to original',
    'admin.news.form.submit': 'Publish article',
    'admin.news.form.submitUpdate': 'Save changes',
    'admin.news.form.submitting': 'Publishing...',
    'admin.news.delete.title': 'Delete article',
    'admin.news.delete.description': 'Are you sure you want to delete “{title}”?',
    'admin.news.delete.confirm': 'Delete article',
    'admin.news.delete.cancel': 'Keep article',

    // Footer
    'footer.title': 'AIPHARM+',
    'footer.description': 'Quality medicines with AI consultations and fast delivery.',
    'footer.version': 'Version {version}',
    'footer.quickLinks': 'Quick Links',
    'footer.aboutUs': 'About Us',
    'footer.products': 'Products',
    'footer.services': 'Services',
    'footer.contacts': 'Contacts',
    'footer.promotions': 'Promotions',
    'footer.news': 'News',
    'footer.faq': 'FAQ',
    'footer.contactsTitle': 'Contact Info',
    'footer.workingHours': 'Working Hours',
    'footer.workingHoursText': 'Mon-Fri: 8:00 - 22:00\nSat-Sun: 9:00 - 20:00',
    'footer.copyright': '© 2025 AIPHARM+. All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Use',
    'footer.cookies': 'Cookies',
    'footer.feedbackTitle': 'Share Your Opinion',
    'footer.feedbackDescription': 'Your insights help us improve AIPHARM+ and its services. Let us know what you think about the site and the project.',
    'footer.ratingLabel': 'Rating',
    'footer.starsLabel': 'stars',
    'footer.messageLabel': 'Review',
    'footer.messagePlaceholder': 'Tell us what stands out to you and how we can enhance your experience...',
    'footer.feedbackPrivacy': 'Your opinion will be sent directly to the AIPHARM+ team via email',
    'footer.submitButton': 'Send Email',
    'footer.feedbackEmailSubject': 'Feedback for AIPHARM+',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.price': 'Price',
    'common.quantity': 'Quantity',
    'common.total': 'Total',
    'common.currency': '€',

    // About Us
    'about.description': 'AIPHARM+ is a leading digital pharmacy in Bulgaria, combining traditional pharmaceutical care with the latest AI technologies.',
    'about.mission': 'Our Mission',
    'about.missionText': 'To provide quality medicines and health products with personalized AI consultations, ensuring accessible and reliable healthcare for everyone.',
    'about.vision': 'Our Vision',
    'about.visionText': 'To be the most trusted digital pharmacy in Bulgaria, revolutionizing the way people receive medical advice and medicines.',
    'about.quality': 'Quality',
    'about.qualityText': 'All our products are certified and approved by the Bulgarian Drug Agency.',
    'about.speed': 'Speed',
    'about.speedText': 'Express delivery within 2 hours in Sofia and up to 24 hours nationwide.',
    'about.care': 'Care',
    'about.careText': '24/7 AI assistant and professional pharmacists at your service.',
    'about.clients': 'Satisfied Clients',
    'about.products': 'Products in Stock',
    'about.experience': 'Years Experience',
    'about.support': 'Support',

    // Services
    'services.pageTitle': 'Our services',
    'services.pageDescription': 'We combine digital innovation with professional pharmaceutical care.',
    'services.aiConsultationsTitle': 'AI health consultations',
    'services.aiConsultationsDescription': 'A virtual assistant that provides evidence-based recommendations and tracks your symptoms.',
    'services.aiConsultationsFeature1': 'Personalised medicine recommendations',
    'services.aiConsultationsFeature2': 'Real-time symptom analysis',
    'services.aiConsultationsFeature3': 'Escalation to a pharmacist when needed',
    'services.telepharmacyTitle': 'Telepharmacy experts',
    'services.telepharmacyDescription': 'Licensed pharmacists supporting you remotely.',
    'services.telepharmacyFeature1': 'Video consultations and live chat',
    'services.telepharmacyFeature2': 'Medication interaction checks',
    'services.telepharmacyFeature3': 'Therapy monitoring and follow-up calls',
    'services.deliveryTitle': 'Logistics & delivery',
    'services.deliveryDescription': 'In-house network for fast and safe deliveries nationwide.',
    'services.deliveryFeature1': 'Express two-hour deliveries in Sofia',
    'services.deliveryFeature2': 'Real-time order tracking',
    'services.deliveryFeature3': 'Temperature-controlled transport',
    'services.valueTitle': 'Why choose AIPHARM+',
    'services.valueSubtitle': 'We bring together safety, expertise, and convenience.',
    'services.valuePatients': 'Patient care',
    'services.valuePatientsDesc': 'Individual plans and medicine intake reminders.',
    'services.valueData': 'Data security',
    'services.valueDataDesc': 'Fully encrypted platform with continuous monitoring.',
    'services.valueSupport': '24/7 support',
    'services.valueSupportDesc': 'Specialists available via phone, chat, and email.',
    'services.ctaTitle': 'Need a personal consultation?',
    'services.ctaDescription': 'Contact us and we will guide you to the right service.',
    'services.ctaButton': 'Speak with an expert',

    // Contacts
    'contacts.description': 'Contact us anytime. Our team is ready to help you with all your questions.',
    'contacts.info': 'Contact Information',
    'contacts.phone': 'Phone',
    'contacts.email': 'Email',
    'contacts.address': 'Address',
    'contacts.emergency': 'Emergency Cases',
    'contacts.emergencyText': 'For medical emergencies, please contact emergency services.',
    'contacts.emergencyNumber': 'Emergency Number',
    'contacts.sendMessage': 'Send Message',
    'contacts.firstName': 'First Name',
    'contacts.lastName': 'Last Name',
    'contacts.subject': 'Subject',
    'contacts.message': 'Message',
    'contacts.send': 'Send',
    'contacts.firstNamePlaceholder': 'Your first name',
    'contacts.lastNamePlaceholder': 'Your last name',
    'contacts.emailPlaceholder': 'your@email.com',
    'contacts.subjectPlaceholder': 'Message subject',
    'contacts.messagePlaceholder': 'Write your message here...',

    // Promotions
    'promotions.description': 'Discover our current promotions and save on medicines and health products.',
    'promotions.currentCount': '{count} active offers',
    'promotions.activeOffers': 'Active offers',
    'promotions.averageDiscount': 'Average discount',
    'promotions.highestDiscount': 'Highest discount: {value}%',
    'promotions.estimatedSavings': 'Potential savings',
    'promotions.limitedStock': 'Offers are valid while stocks last',
    'promotions.noActive': 'There are no active promotions at the moment.',
    'promotions.freeDelivery': 'Free Delivery',
    'promotions.freeDeliveryDesc': 'Free delivery for all orders over €25 nationwide.',
    'promotions.vitamins20': '20% off Vitamins',
    'promotions.vitamins20Desc': 'Special promotion on all vitamins and dietary supplements.',
    'promotions.firstOrder': 'First Order',
    'promotions.firstOrderDesc': '15% discount for new customers on their first order.',
    'promotions.loyaltyProgram': 'Loyalty Program',
    'promotions.loyaltyProgramDesc': 'Collect points with every purchase and get discounts.',
    'promotions.free': 'Free',
    'promotions.points': 'Points',
    'promotions.permanent': 'Permanent',
    'promotions.discount': 'discount',
    'promotions.validUntil': 'Valid until',
    'promotions.useNow': 'Use now',
    'promotions.howToUse': 'How to use promotions',
    'promotions.step1': 'Select products',
    'promotions.step1Desc': 'Add desired products to your cart.',
    'promotions.step2': 'Apply code',
    'promotions.step2Desc': 'Enter promo code at checkout.',
    'promotions.step3': 'Save money',
    'promotions.step3Desc': 'Get the discount and complete your order.',

    // News
    'news.title': 'News & helpful insights',
    'news.subtitle': 'Latest trends, recommendations and analysis from our pharmacists and specialists.',
    'news.latest': 'Latest posts',
    'news.readMore': 'Read more',
    'news.showLess': 'Show less',
    'news.readTime': '{minutes} min read',
    'news.published': 'Published on',
    'news.authorBy': 'Author:',

    // FAQ
    'faq.description': 'Find answers to the most frequently asked questions about our services.',
    'faq.searchPlaceholder': 'Search question...',
    'faq.noResults': 'No results found',
    'faq.tryDifferent': 'Try different keywords.',
    'faq.stillNeedHelp': 'Still need help?',
    'faq.contactSupport': 'Our support team is ready to help you.',
    'faq.callUs': 'Call Us',
    'faq.emailUs': 'Email Us',
    'faq.q1': 'How long does delivery take?',
    'faq.a1': 'Delivery in Sofia takes up to 2 hours, and in the rest of the country - up to 24 hours. For urgent cases, we offer express delivery.',
    'faq.q2': 'What payment methods do you accept?',
    'faq.a2': 'We accept payments with debit and credit cards, bank transfer, as well as cash on delivery.',
    'faq.q3': 'Do I need a prescription for all medicines?',
    'faq.a3': 'No, many medicines are over-the-counter. Products that require a prescription are clearly marked on the site.',
    'faq.q4': 'How does the AI assistant work?',
    'faq.a4': 'Our AI assistant provides general information about medicines. Always consult with a doctor for personalized advice.',
    'faq.q5': 'Can I return a product?',
    'faq.a5': 'Yes, you can return unopened products within 14 days of purchase, according to consumer protection law.',
    'faq.q6': 'How do I create an account?',
    'faq.a6': 'Click "Register" in the top right corner and fill in the required information. Your account will be activated immediately.',
    'faq.q7': 'Do you deliver outside Sofia?',
    'faq.a7': 'Yes, we deliver nationwide. Delivery outside Sofia takes up to 24 hours.',
    'faq.q8': 'Is my personal data safe?',
    'faq.a8': 'Yes, we use the highest standards for data security and encryption. Your information is completely protected.'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('bg');

  const t = (key: string, params?: TranslationParams): string => {
    const template =
      translations[language][key as keyof (typeof translations)['bg']] ||
      translations.bg[key as keyof (typeof translations)['bg']] ||
      key;

    if (!params) {
      return template;
    }

    return Object.entries(params).reduce((result, [paramKey, value]) => {
      const pattern = new RegExp(`{${paramKey}}`, 'g');
      return result.replace(pattern, String(value));
    }, template);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};